### ISSUE TITLE
vue-tsc: "parameter should have errors when reporting errors"

### ISSUE THREAD

**Issue by oswaldofreitas** [vuejs/language-tools#2270]
I'm getting this error when running `npx vue-tsc --noEmit`
```
/my-proj/node_modules/vue-tsc/bin/vue-tsc.js:46
                        throw err;
                        ^

Error: Debug Failure. False expression: parameter should have errors when reporting errors
    at getSignatureApplicabilityError (/my-proj/node_modules/typescript/lib/typescript.js:77401:34)
    at resolveCall (/my-proj/node_modules/typescript/lib/typescript.js:77803:37)
    at resolveCallExpression (/my-proj/node_modules/typescript/lib/typescript.js:78187:20)
    at resolveSignature (/my-proj/node_modules/typescript/lib/typescript.js:78570:28)
    at getResolvedSignature (/my-proj/node_modules/typescript/lib/typescript.js:78601:26)
    at checkCallExpression (/my-proj/node_modules/typescript/lib/typescript.js:78729:29)
    at checkExpressionWorker (/my-proj/node_modules/typescript/lib/typescript.js:81616:28)
    at checkExpression (/my-proj/node_modules/typescript/lib/typescript.js:81520:38)
    at checkExpressionStatement (/my-proj/node_modules/typescript/lib/typescript.js:84444:13)
    at checkSourceElementWorker (/my-proj/node_modules/typescript/lib/typescript.js:87611:28)
```

**Comment by johnsoncodehk** [comment]
What is your typescript version? If you're using a newer typescript version, try if downgrading typescript can fix it.

**Comment by oswaldofreitas** [comment]
I'm using Typescript 4.8.4

**Comment by Meesayen** [comment]
I'm getting this error with latest vue-tsc (1.0.24) and typescript 4.9.4

**Comment by johnsoncodehk** [comment]
As far as I know this is a bug of TS, please provide a repro case so that we can report it to TS.
