### ISSUE TITLE
Vue Semantic Server crashing from JSDoc

### ISSUE THREAD

**Issue by robjweiss** [vuejs/language-tools#2327]
Versions
- Node 14.17
- TypeScript
- Vue 2.7.0
- VS Code 1.74.3
- Mac OS

When I have JSDoc comments in `<script setup lang="ts">` Volar seems to run into the following issues:
```
TypeError: Cannot read properties of undefined (reading 'text')
    at getTokenPosOfNode (/Users/rob/dev/project/node_modules/typescript/lib/typescript.js:13049:76)
    at Object.getTokenPosOfNode (/Users/rob/dev/project/node_modules/typescript/lib/typescript.js:13052:20)
    at NodeObject.getStart (/Users/rob/dev/project/node_modules/typescript/lib/typescript.js:134727:23)
    at /Users/rob/.vscode/extensions/vue.volar-1.0.24-darwin-arm64/dist/node/server.js:877:614
    at visitNodes (/Users/rob/dev/project/node_modules/typescript/lib/typescript.js:18440:30)
    at Object.forEachChild (/Users/rob/dev/project/node_modules/typescript/lib/typescript.js:18673:24)
    at NodeObject.forEachChild (/Users/rob/dev/project/node_modules/typescript/lib/typescript.js:134791:23)
    at SDe (/Users/rob/.vscode/extensions/vue.volar-1.0.24-darwin-arm64/dist/node/server.js:877:338)
    at w1.fn (/Users/rob/.vscode/extensions/vue.volar-1.0.24-darwin-arm64/dist/node/server.js:881:713)
    at w1.run (/Users/rob/.vscode/extensions/vue.volar-1.0.24-darwin-arm64/dist/node/server.js:781:6814)
/Users/rob/dev/project/node_modules/typescript/lib/typescript.js:13049
            return ts.skipTrivia((sourceFile || getSourceFileOfNode(node)).text, node.pos, /*stopAfterLineBreak*/ false, /*stopAtComments*/ true);
                                                                           ^

TypeError: Cannot read properties of undefined (reading 'text')
    at getTokenPosOfNode (/Users/rob/dev/project/node_modules/typescript/lib/typescript.js:13049:76)
    at Object.getTokenPosOfNode (/Users/rob/dev/project/node_modules/typescript/lib/typescript.js:13052:20)
    at NodeObject.getStart (/Users/rob/dev/project/node_modules/typescript/lib/typescript.js:134727:23)
    at /Users/rob/.vscode/extensions/vue.volar-1.0.24-darwin-arm64/dist/node/server.js:877:614
    at visitNodes (/Users/rob/dev/project/node_modules/typescript/lib/typescript.js:18440:30)
    at Object.forEachChild (/Users/rob/dev/project/node_modules/typescript/lib/typescript.js:18673:24)
    at NodeObject.forEachChild (/Users/rob/dev/project/node_modules/typescript/lib/typescript.js:134791:23)
    at SDe (/Users/rob/.vscode/extensions/vue.volar-1.0.24-darwin-arm64/dist/node/server.js:877:338)
    at /Users/rob/.vscode/extensions/vue.volar-1.0.24-darwin-arm64/dist/node/server.js:1017:12173
    at u (/Users/rob/.vscode/extensions/vue.volar-1.0.24-darwin-arm64/dist/node/server.js:1017:14598)
[Info  - 4:04:09 PM] Connection to server got closed. Server will restart.
TypeError: Cannot read properties of undefined (reading 'text')
    at getTokenPosOfNode (/Users/rob/dev/project/node_modules/typescript/lib/typescript.js:13049:76)
    at Object.getTokenPosOfNode (/Users/rob/dev/project/node_modules/typescript/lib/typescript.js:13052:20)
    at NodeObject.getStart (/Users/rob/dev/project/node_modules/typescript/lib/typescript.js:134727:23)
    at /Users/rob/.vscode/extensions/vue.volar-1.0.24-darwin-arm64/dist/node/server.js:877:614
    at visitNodes (/Users/rob/dev/project/node_modules/typescript/lib/typescript.js:18440:30)
    at Object.forEachChild (/Users/rob/dev/project/node_modules/typescript/lib/typescript.js:18673:24)
    at NodeObject.forEachChild (/Users/rob/dev/project/node_modules/typescript/lib/typescript.js:134791:23)
    at SDe (/Users/rob/.vscode/extensions/vue.volar-1.0.24-darwin-arm64/dist/node/server.js:877:338)
    at w1.fn (/Users/rob/.vscode/extensions/vue.volar-1.0.24-darwin-arm64/dist/node/server.js:881:713)
    at w1.run (/Users/rob/.vscode/extensions/vue.volar-1.0.24-darwin-arm64/dist/node/server.js:781:6814)
TypeError: Cannot read properties of undefined (reading 'text')
    at getTokenPosOfNode (/Users/rob/dev/project/node_modules/typescript/lib/typescript.js:13049:76)
    at Object.getTokenPosOfNode (/Users/rob/dev/project/node_modules/typescript/lib/typescript.js:13052:20)
    at NodeObject.getStart (/Users/rob/dev/project/node_modules/typescript/lib/typescript.js:134727:23)
    at /Users/rob/.vscode/extensions/vue.volar-1.0.24-darwin-arm64/dist/node/server.js:877:614
    at visitNodes (/Users/rob/dev/project/node_modules/typescript/lib/typescript.js:18440:30)
    at Object.forEachChild (/Users/rob/dev/project/node_modules/typescript/lib/typescript.js:18673:24)
    at NodeObject.forEachChild (/Users/rob/dev/project/node_modules/typescript/lib/typescript.js:134791:23)
    at SDe (/Users/rob/.vscode/extensions/vue.volar-1.0.24-darwin-arm64/dist/node/server.js:877:338)
    at w1.fn (/Users/rob/.vscode/extensions/vue.volar-1.0.24-darwin-arm64/dist/node/server.js:881:713)
    at w1.run (/Users/rob/.vscode/extensions/vue.volar-1.0.24-darwin-arm64/dist/node/server.js:781:6814)
/Users/rob/dev/project/node_modules/typescript/lib/typescript.js:13049
            return ts.skipTrivia((sourceFile || getSourceFileOfNode(node)).text, node.pos, /*stopAfterLineBreak*/ false, /*stopAtComments*/ true);
                                                                           ^

TypeError: Cannot read properties of undefined (reading 'text')
    at getTokenPosOfNode (/Users/rob/dev/project/node_modules/typescript/lib/typescript.js:13049:76)
    at Object.getTokenPosOfNode (/Users/rob/dev/project/node_modules/typescript/lib/typescript.js:13052:20)
    at NodeObject.getStart (/Users/rob/dev/project/node_modules/typescript/lib/typescript.js:134727:23)
    at /Users/rob/.vscode/extensions/vue.volar-1.0.24-darwin-arm64/dist/node/server.js:877:614
    at visitNodes (/Users/rob/dev/project/node_modules/typescript/lib/typescript.js:18440:30)
    at Object.forEachChild (/Users/rob/dev/project/node_modules/typescript/lib/typescript.js:18673:24)
    at NodeObject.forEachChild (/Users/rob/dev/project/node_modules/typescript/lib/typescript.js:134791:23)
    at SDe (/Users/rob/.vscode/extensions/vue.volar-1.0.24-darwin-arm64/dist/node/server.js:877:338)
    at /Users/rob/.vscode/extensions/vue.volar-1.0.24-darwin-arm64/dist/node/server.js:1017:12173
    at u (/Users/rob/.vscode/extensions/vue.volar-1.0.24-darwin-arm64/dist/node/server.js:1017:14598)
[Info  - 4:04:11 PM] Connection to server got closed. Server will restart.
TypeError: Cannot read properties of undefined (reading 'text')
    at getTokenPosOfNode (/Users/rob/dev/project/node_modules/typescript/lib/typescript.js:13049:76)
    at Object.getTokenPosOfNode (/Users/rob/dev/project/node_modules/typescript/lib/typescript.js:13052:20)
    at NodeObject.getStart (/Users/rob/dev/project/node_modules/typescript/lib/typescript.js:134727:23)
    at /Users/rob/.vscode/extensions/vue.volar-1.0.24-darwin-arm64/dist/node/server.js:877:614
    at visitNodes (/Users/rob/dev/project/node_modules/typescript/lib/typescript.js:18440:30)
    at Object.forEachChild (/Users/rob/dev/project/node_modules/typescript/lib/typescript.js:18673:24)
    at NodeObject.forEachChild (/Users/rob/dev/project/node_modules/typescript/lib/typescript.js:134791:23)
    at SDe (/Users/rob/.vscode/extensions/vue.volar-1.0.24-darwin-arm64/dist/node/server.js:877:338)
    at w1.fn (/Users/rob/.vscode/extensions/vue.volar-1.0.24-darwin-arm64/dist/node/server.js:881:713)
    at w1.run (/Users/rob/.vscode/extensions/vue.volar-1.0.24-darwin-arm64/dist/node/server.js:781:6814)
/Users/rob/dev/project/node_modules/typescript/lib/typescript.js:13049
            return ts.skipTrivia((sourceFile || getSourceFileOfNode(node)).text, node.pos, /*stopAfterLineBreak*/ false, /*stopAtComments*/ true);
                                                                           ^

TypeError: Cannot read properties of undefined (reading 'text')
    at getTokenPosOfNode (/Users/rob/dev/project/node_modules/typescript/lib/typescript.js:13049:76)
    at Object.getTokenPosOfNode (/Users/rob/dev/project/node_modules/typescript/lib/typescript.js:13052:20)
    at NodeObject.getStart (/Users/rob/dev/project/node_modules/typescript/lib/typescript.js:134727:23)
    at /Users/rob/.vscode/extensions/vue.volar-1.0.24-darwin-arm64/dist/node/server.js:877:614
    at visitNodes (/Users/rob/dev/project/node_modules/typescript/lib/typescript.js:18440:30)
    at Object.forEachChild (/Users/rob/dev/project/node_modules/typescript/lib/typescript.js:18673:24)
    at NodeObject.forEachChild (/Users/rob/dev/project/node_modules/typescript/lib/typescript.js:134791:23)
    at SDe (/Users/rob/.vscode/extensions/vue.volar-1.0.24-darwin-arm64/dist/node/server.js:877:338)
    at /Users/rob/.vscode/extensions/vue.volar-1.0.24-darwin-arm64/dist/node/server.js:1017:12173
    at u (/Users/rob/.vscode/extensions/vue.volar-1.0.24-darwin-arm64/dist/node/server.js:1017:14598)
[Info  - 4:04:13 PM] Connection to server got closed. Server will restart.
TypeError: Cannot read properties of undefined (reading 'text')
    at getTokenPosOfNode (/Users/rob/dev/project/node_modules/typescript/lib/typescript.js:13049:76)
    at Object.getTokenPosOfNode (/Users/rob/dev/project/node_modules/typescript/lib/typescript.js:13052:20)
    at NodeObject.getStart (/Users/rob/dev/project/node_modules/typescript/lib/typescript.js:134727:23)
    at /Users/rob/.vscode/extensions/vue.volar-1.0.24-darwin-arm64/dist/node/server.js:877:614
    at visitNodes (/Users/rob/dev/project/node_modules/typescript/lib/typescript.js:18440:30)
    at Object.forEachChild (/Users/rob/dev/project/node_modules/typescript/lib/typescript.js:18673:24)
    at NodeObject.forEachChild (/Users/rob/dev/project/node_modules/typescript/lib/typescript.js:134791:23)
    at SDe (/Users/rob/.vscode/extensions/vue.volar-1.0.24-darwin-arm64/dist/node/server.js:877:338)
    at w1.fn (/Users/rob/.vscode/extensions/vue.volar-1.0.24-darwin-arm64/dist/node/server.js:881:713)
    at w1.run (/Users/rob/.vscode/extensions/vue.volar-1.0.24-darwin-arm64/dist/node/server.js:781:6814)
TypeError: Cannot read properties of undefined (reading 'text')
    at getTokenPosOfNode (/Users/rob/dev/project/node_modules/typescript/lib/typescript.js:13049:76)
    at Object.getTokenPosOfNode (/Users/rob/dev/project/node_modules/typescript/lib/typescript.js:13052:20)
    at NodeObject.getStart (/Users/rob/dev/project/node_modules/typescript/lib/typescript.js:134727:23)
    at /Users/rob/.vscode/extensions/vue.volar-1.0.24-darwin-arm64/dist/node/server.js:877:614
    at visitNodes (/Users/rob/dev/project/node_modules/typescript/lib/typescript.js:18440:30)
    at Object.forEachChild (/Users/rob/dev/project/node_modules/typescript/lib/typescript.js:18673:24)
    at NodeObject.forEachChild (/Users/rob/dev/project/node_modules/typescript/lib/typescript.js:134791:23)
    at SDe (/Users/rob/.vscode/extensions/vue.volar-1.0.24-darwin-arm64/dist/node/server.js:877:338)
    at w1.fn (/Users/rob/.vscode/extensions/vue.volar-1.0.24-darwin-arm64/dist/node/server.js:881:713)
    at w1.run (/Users/rob/.vscode/extensions/vue.volar-1.0.24-darwin-arm64/dist/node/server.js:781:6814)
/Users/rob/dev/project/node_modules/typescript/lib/typescript.js:13049
            return ts.skipTrivia((sourceFile || getSourceFileOfNode(node)).text, node.pos, /*stopAfterLineBreak*/ false, /*stopAtComments*/ true);
                                                                           ^

TypeError: Cannot read properties of undefined (reading 'text')
    at getTokenPosOfNode (/Users/rob/dev/project/node_modules/typescript/lib/typescript.js:13049:76)
    at Object.getTokenPosOfNode (/Users/rob/dev/project/node_modules/typescript/lib/typescript.js:13052:20)
    at NodeObject.getStart (/Users/rob/dev/project/node_modules/typescript/lib/typescript.js:134727:23)
    at /Users/rob/.vscode/extensions/vue.volar-1.0.24-darwin-arm64/dist/node/server.js:877:614
    at visitNodes (/Users/rob/dev/project/node_modules/typescript/lib/typescript.js:18440:30)
    at Object.forEachChild (/Users/rob/dev/project/node_modules/typescript/lib/typescript.js:18673:24)
    at NodeObject.forEachChild (/Users/rob/dev/project/node_modules/typescript/lib/typescript.js:134791:23)
    at SDe (/Users/rob/.vscode/extensions/vue.volar-1.0.24-darwin-arm64/dist/node/server.js:877:338)
    at /Users/rob/.vscode/extensions/vue.volar-1.0.24-darwin-arm64/dist/node/server.js:1017:12173
    at u (/Users/rob/.vscode/extensions/vue.volar-1.0.24-darwin-arm64/dist/node/server.js:1017:14598)
[Info  - 4:04:14 PM] Connection to server got closed. Server will restart.
TypeError: Cannot read properties of undefined (reading 'text')
    at getTokenPosOfNode (/Users/rob/dev/project/node_modules/typescript/lib/typescript.js:13049:76)
    at Object.getTokenPosOfNode (/Users/rob/dev/project/node_modules/typescript/lib/typescript.js:13052:20)
    at NodeObject.getStart (/Users/rob/dev/project/node_modules/typescript/lib/typescript.js:134727:23)
    at /Users/rob/.vscode/extensions/vue.volar-1.0.24-darwin-arm64/dist/node/server.js:877:614
    at visitNodes (/Users/rob/dev/project/node_modules/typescript/lib/typescript.js:18440:30)
    at Object.forEachChild (/Users/rob/dev/project/node_modules/typescript/lib/typescript.js:18673:24)
    at NodeObject.forEachChild (/Users/rob/dev/project/node_modules/typescript/lib/typescript.js:134791:23)
    at SDe (/Users/rob/.vscode/extensions/vue.volar-1.0.24-darwin-arm64/dist/node/server.js:877:338)
    at w1.fn (/Users/rob/.vscode/extensions/vue.volar-1.0.24-darwin-arm64/dist/node/server.js:881:713)
    at w1.run (/Users/rob/.vscode/extensions/vue.volar-1.0.24-darwin-arm64/dist/node/server.js:781:6814)
TypeError: Cannot read properties of undefined (reading 'text')
    at getTokenPosOfNode (/Users/rob/dev/project/node_modules/typescript/lib/typescript.js:13049:76)
    at Object.getTokenPosOfNode (/Users/rob/dev/project/node_modules/typescript/lib/typescript.js:13052:20)
    at NodeObject.getStart (/Users/rob/dev/project/node_modules/typescript/lib/typescript.js:134727:23)
    at /Users/rob/.vscode/extensions/vue.volar-1.0.24-darwin-arm64/dist/node/server.js:877:614
    at visitNodes (/Users/rob/dev/project/node_modules/typescript/lib/typescript.js:18440:30)
    at Object.forEachChild (/Users/rob/dev/project/node_modules/typescript/lib/typescript.js:18673:24)
    at NodeObject.forEachChild (/Users/rob/dev/project/node_modules/typescript/lib/typescript.js:134791:23)
    at SDe (/Users/rob/.vscode/extensions/vue.volar-1.0.24-darwin-arm64/dist/node/server.js:877:338)
    at w1.fn (/Users/rob/.vscode/extensions/vue.volar-1.0.24-darwin-arm64/dist/node/server.js:881:713)
    at w1.run (/Users/rob/.vscode/extensions/vue.volar-1.0.24-darwin-arm64/dist/node/server.js:781:6814)
/Users/rob/dev/project/node_modules/typescript/lib/typescript.js:13049
            return ts.skipTrivia((sourceFile || getSourceFileOfNode(node)).text, node.pos, /*stopAfterLineBreak*/ false, /*stopAtComments*/ true);
                                                                           ^

TypeError: Cannot read properties of undefined (reading 'text')
    at getTokenPosOfNode (/Users/rob/dev/project/node_modules/typescript/lib/typescript.js:13049:76)
    at Object.getTokenPosOfNode (/Users/rob/dev/project/node_modules/typescript/lib/typescript.js:13052:20)
    at NodeObject.getStart (/Users/rob/dev/project/node_modules/typescript/lib/typescript.js:134727:23)
    at /Users/rob/.vscode/extensions/vue.volar-1.0.24-darwin-arm64/dist/node/server.js:877:614
    at visitNodes (/Users/rob/dev/project/node_modules/typescript/lib/typescript.js:18440:30)
    at Object.forEachChild (/Users/rob/dev/project/node_modules/typescript/lib/typescript.js:18673:24)
    at NodeObject.forEachChild (/Users/rob/dev/project/node_modules/typescript/lib/typescript.js:134791:23)
    at SDe (/Users/rob/.vscode/extensions/vue.volar-1.0.24-darwin-arm64/dist/node/server.js:877:338)
    at /Users/rob/.vscode/extensions/vue.volar-1.0.24-darwin-arm64/dist/node/server.js:1017:12173
    at u (/Users/rob/.vscode/extensions/vue.volar-1.0.24-darwin-arm64/dist/node/server.js:1017:14598)
[Error - 4:04:16 PM] The Vue Semantic Server server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
```
If there are enough JSDoc comments the server crashes.

A JSDoc comment like this triggers the issue:
```ts
/**
 * State
 */
const foo = ref(false)
```

Wrapping with regular comments ameliorates the issue:
```ts
// /**
//  * State
//  */
const foo = ref(false)
```

**Comment by johnsoncodehk** [comment]
> If there are enough JSDoc comments the server crashes.

Can you provide a real example that triggers the problem?
