### ISSUE TITLE
Typescript 5.0 (beta) support

### ISSUE THREAD

**Issue by patroza** [vuejs/language-tools#2343]
Typescript 5.0 beta was released https://devblogs.microsoft.com/typescript/announcing-typescript-5-0-beta/
But typing inside template attributes doesn't work with it:
```
components/TextArea.vue:5:26 - error TS7006: Parameter 'value' implicitly has an 'any' type.

@update:model-value="value => convertOut(value, updateValue)"
```

```
components/Some.vue:62:28 - error TS7006: Parameter '_' implicitly has an 'any' type.

v-if="items.some(_ => _.state._tag === 'Open')"
```

tested in latest vue-tsc.

**Comment by johnsoncodehk** [comment]
I can't reproduce the problem, please provide minimal reproduction, and make sure you have update vue-tsc to latest.

**Comment by patroza** [comment]
@johnsoncodehk the error seems to come especially with `vue-tsc -w`, and not with just `vue-tsc`

**Comment by patroza** [comment]
@johnsoncodehk here's a repro
https://github.com/patroza/vue-tsc-repro

`npm I`
`npm run vue-tsc -w`

**Comment by patroza** [comment]
@johnsoncodehk do you have some pointers, maybe I could help

**Comment by patroza** [comment]
@johnsoncodehk in the meantime 5.0 final was released

**Comment by segevfiner** [comment]
Enabling `"verbatimModuleSyntax": true` also causes the following error in a plain `create-vue@3` project with TS upgraded to TS 5.0.2:

```
❯ pnpm type-check

> vue-ts5@0.0.0 type-check /Users/segevfiner/junk/vue-ts5
> vue-tsc --noEmit -p tsconfig.vitest.json --composite false

/Users/segevfiner/junk/vue-ts5/node_modules/.pnpm/vue-tsc@1.2.0_typescript@5.0.2/node_modules/vue-tsc/bin/vue-tsc.js:43
                        throw err;
                        ^

Error: Debug Failure. False expression.
    at isReferencedAliasDeclaration (/Users/segevfiner/junk/vue-ts5/node_modules/.pnpm/typescript@5.0.2/node_modules/typescript/lib/typescript.js:82757:13)
    at canConvertImportDeclarationToTypeOnly (/Users/segevfiner/junk/vue-ts5/node_modules/.pnpm/typescript@5.0.2/node_modules/typescript/lib/typescript.js:81296:177)
    at checkImportsForTypeOnlyConversion (/Users/segevfiner/junk/vue-ts5/node_modules/.pnpm/typescript@5.0.2/node_modules/typescript/lib/typescript.js:81311:13)
    at checkSourceFileWorker (/Users/segevfiner/junk/vue-ts5/node_modules/.pnpm/typescript@5.0.2/node_modules/typescript/lib/typescript.js:81874:11)
    at checkSourceFile (/Users/segevfiner/junk/vue-ts5/node_modules/.pnpm/typescript@5.0.2/node_modules/typescript/lib/typescript.js:81822:7)
    at checkSourceFileWithEagerDiagnostics (/Users/segevfiner/junk/vue-ts5/node_modules/.pnpm/typescript@5.0.2/node_modules/typescript/lib/typescript.js:81916:7)
    at getDiagnosticsWorker (/Users/segevfiner/junk/vue-ts5/node_modules/.pnpm/typescript@5.0.2/node_modules/typescript/lib/typescript.js:81924:9)
    at Object.getDiagnostics2 [as getDiagnostics] (/Users/segevfiner/junk/vue-ts5/node_modules/.pnpm/typescript@5.0.2/node_modules/typescript/lib/typescript.js:81901:16)
    at /Users/segevfiner/junk/vue-ts5/node_modules/.pnpm/typescript@5.0.2/node_modules/typescript/lib/typescript.js:116837:78
    at runWithCancellationToken (/Users/segevfiner/junk/vue-ts5/node_modules/.pnpm/typescript@5.0.2/node_modules/typescript/lib/typescript.js:116807:16)
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by segevfiner** [comment]
It also seems that `vue-tsc --build` will randomly fail resolving `.vue` imports unless ran multiple times.

**Comment by blake-newman** [comment]
https://github.com/vuejs/language-tools/pull/2555

This should resolve this issue

**Comment by blake-newman** [comment]
Xx Ttttt Ttttt SSP pp p
