### ISSUE TITLE
v1.1.2: Nuxt 3.2.0 failure - [uncaughtException] require(...).loadTsLib is not a function

### ISSUE THREAD

**Issue by INRIX-Iurii-Okhmat** [vuejs/language-tools#2397]
- Barebones setup of Nuxt 3.2.0 with Vite (default)
- `vue-tsc` installed as a dependency: ^v1.0.24 (which brings v1.1.2)
- `nuxt.config.ts` has a `typescript: { typeCheck: true }` set 

Fails during build time with the following error 

```
Nuxt 3.2.0 with Nitro 2.2.1  
                                                                                                                                                                   12:28:58
  > Local:    http://localhost:5000/demo/
  > Network:  http://172.16.34.50:5000/demo/

ℹ Vite client warmed up in 3472ms                                                                                                                                  12:29:09
✔ Nitro built in 738 ms                                                                                                                                      nitro 12:29:09

 ERROR  [uncaughtException] require(...).loadTsLib is not a function                                                                                               12:29:12

  at node_modules/vite-plugin-checker/dist/esm/checkers/vueTsc/typescript-vue-tsc/lib/tsc.js:3505:119
  at Object.<anonymous> (node_modules/vite-plugin-checker/dist/esm/checkers/vueTsc/typescript-vue-tsc/lib/tsc.js:3507:3)
  at Module._compile (node:internal/modules/cjs/loader:1226:14)
  at Module._extensions..js (node:internal/modules/cjs/loader:1280:10)
  at Module.load (node:internal/modules/cjs/loader:1089:32)
  at Module._load (node:internal/modules/cjs/loader:930:12)
  at Module.require (node:internal/modules/cjs/loader:1113:19)
  at require (node:internal/modules/cjs/helpers:103:18)
  at Object.configureServer (node_modules/vite-plugin-checker/dist/esm/checkers/vueTsc/main.js:34:21)                                                              12:28:56

```

Downgrading to v1.0.24 fixes the issue:

```
Nuxt 3.2.0 with Nitro 2.2.1                                                                                                                                        12:37:55
                                                                                                                                                                   12:37:57
  > Local:    http://localhost:5000/demo/
  > Network:  http://172.16.34.50:5000/demo/                                                                                                                       12:37:55

ℹ Vite client warmed up in 1362ms                                                                                                                                  12:38:00
✔ Nitro built in 507 ms                                                                                                                                      nitro 12:38:01
                                                                                                                                                                   12:38:03
[vue-tsc] Found 0 errors. Watching for file changes.

```

**Comment by mesqueeb** [comment]
@INRIX-Iurii-Okhmat did you find a work around? I also can't launch our app anymore

**Comment by johnsoncodehk** [comment]
Please track https://github.com/fi3ework/vite-plugin-checker/issues/222.
