### ISSUE TITLE
vue-tsc crashes in watch mode when file changed after 1.1.0

### ISSUE THREAD

**Issue by fi3ework** [vuejs/language-tools#2403]
When fixing vue-plugin-checker https://github.com/fi3ework/vite-plugin-checker/pull/223. I failed to pass the test after bumping vue-tsc to `^1.1.0`. I can reproduce the error with `vue-tsc` only. 

## reproduction:
https://stackblitz.com/edit/vitejs-vite-scrrnu?file=src%2FApp.vue,src%2Fcomponents%2FHelloWorld.vue,package.json

### steps to reproduce:
1. `npx vue-tsc -w --noEmit`
2. edit any .vue file

then crashes with

```txt
TypeError: Cannot read properties of undefined (reading 'languageServiceHost')
    at Object.createProgram (file:///home/projects/vitejs-vite-scrrnu/node_modules/vue-tsc/out/index.js:120:46)
    at Object.createProgram (file:///home/projects/vitejs-vite-scrrnu/node_modules/typescript/lib/tsc.js:98760:197)
    at Object.getBuilderCreationParameters (file:///home/projects/vitejs-vite-scrrnu/node_modules/typescript/lib/tsc.js:102342:29)
    at createEmitAndSemanticDiagnosticsBuilderProgram (file:///home/projects/vitejs-vite-scrrnu/node_modules/typescript/lib/tsc.js:102779:107)
    at host.createProgram (file:///home/projects/vitejs-vite-scrrnu/node_modules/typescript/lib/tsc.js:107911:20)
    at createNewProgram (file:///home/projects/vitejs-vite-scrrnu/node_modules/typescript/lib/tsc.js:105143:30)
    at synchronizeProgram (file:///home/projects/vitejs-vite-scrrnu/node_modules/typescript/lib/tsc.js:105117:17)
    at updateProgram (file:///home/projects/vitejs-vite-scrrnu/node_modules/typescript/lib/tsc.js:105316:21)
    at Timeout.updateProgramWithWatchStatus [as _onTimeout] (file:///home/projects/vitejs-vite-scrrnu/node_modules/typescript/lib/tsc.js:105302:13)
    at listOnTimeout (https://vitejsvitescrrnu-zxee-9vjzd2y3.w-credentialless.staticblitz.com/blitz.927bd077ab89da68c6338c4363cc22e79cccb4ef.js:6:306542)
```

**Comment by johnsoncodehk** [comment]
Thanks for the report!

**Comment by blake-newman** [comment]
@johnsoncodehk fyi i've got the latest versions installed and I uncommented the lines and i'm not experiencing this issue. 

🤔 

Uncommenting significantly improves the incremental build times for larger projects.

**Comment by blake-newman** [comment]
@johnsoncodehk So not sure why my project doesn't face the same issues in watch mode, but i managed to reproduce the issue and apply a fix.
