### ISSUE TITLE
TypeError: Cannot read properties of null

### ISSUE THREAD

**Issue by sschneider-ihre-pvs** [vuejs/language-tools#2492]
Type: <b>Bug</b>
It seems that volar does not find plugins in monorepo environments
```
2023-03-06 11:53:59.449 [error] TypeError: Cannot read properties of null (reading 'indexOf')
	at <HOME>\.vscode\extensions\vue.volar-1.2.0-win32-x64\dist\node\client.js:59:428
	at Array.some (<anonymous>)
	at <HOME>\.vscode\extensions\vue.volar-1.2.0-win32-x64\dist\node\client.js:59:418
	at Generator.next (<anonymous>)
	at a (<HOME>\.vscode\extensions\vue.volar-1.2.0-win32-x64\dist\node\client.js:42:39708)
```

Extension version: 1.2.0
VS Code version: Code 1.76.0 (92da9481c0904c6adfe372c12da3b7748d74bdcb, 2023-03-01T10:22:44.506Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 PRO 5875U with Radeon Graphics      (16 x 1996)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|46.80GB (26.30GB free)|
|Process Argv|--crash-reporter-id 2ecdc59c-7d55-48a0-beaf-451bf71a6cf4|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vscaat:30438848
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
pyindex848:30662994
nodejswelcome1:30587005
282f8724:30602487
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
2i9eh265:30646982
showlangstatbar:30672706
vsccsb:30677849
pythonms35cf:30676801

```

</details>

**Comment by theRenard** [comment]
Got a similar error that terminate the extension host of VSC

```
2023-03-09 15:17:38.585 [error] TypeError: Cannot read properties of null (reading 'indexOf')
    at /Users/me/.vscode/extensions/vue.volar-1.2.0-darwin-x64/dist/node/client.js:59:428
    at Array.some (<anonymous>)
    at /Users/me/.vscode/extensions/vue.volar-1.2.0-darwin-x64/dist/node/client.js:59:418
    at Generator.next (<anonymous>)
    at a (/Users/me/.vscode/extensions/vue.volar-1.2.0-darwin-x64/dist/node/client.js:42:39708)
```

![image](https://user-images.githubusercontent.com/61255863/224053422-146f383d-2ea5-4d20-a19a-b18d0be16551.png)

**Comment by johnsoncodehk** [comment]
Thanks for the report, it should be fixed with the latest commits, you can update to 1.3.x pre-release for now to avoid the error.
