### ISSUE TITLE
Server crashed, "Pending response rejected since connection got disposed" - How to debug?

### ISSUE THREAD

**Issue by leegee** [vuejs/language-tools#2575]
![image](https://user-images.githubusercontent.com/512816/229448890-ca20c0f2-f35d-46ab-915b-b042d18e4e6b.png)

VSC error toast:

```
Client Vue Semantic Server: connection to server is erroring. Shutting down server.
```

VSC "Output" tab:
```
[Error - 10:03:56 AM] Stopping server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 10:03:56 AM] Stopping server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097 
```

Opened my project, *did a little variable renaming across the whole codebase*, and got the above error. It's a large, commercial project, so I can't share anything, and I have no idea where to begin to gather information, or how to debug this.

Latest VSC, on Win 10.

I uninstalled the extension, restarted VSC, and reinstalled.

![image](https://user-images.githubusercontent.com/512816/229449988-ecc087a1-fbef-4602-9d2a-626529c4f854.png)

```
h:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\typescript.js:82757
      Debug.assert(!compilerOptions.verbatimModuleSyntax);
            ^

Error: Debug Failure. False expression.
    at isReferencedAliasDeclaration (h:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\typescript.js:82757:13)
    at canConvertImportDeclarationToTypeOnly (h:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\typescript.js:81296:177)
    at checkImportsForTypeOnlyConversion (h:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\typescript.js:81311:13)
    at checkSourceFileWorker (h:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\typescript.js:81874:11)
    at checkSourceFile (h:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\typescript.js:81822:7)
    at checkSourceFileWithEagerDiagnostics (h:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\typescript.js:81916:7)
    at getDiagnosticsWorker (h:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\typescript.js:81924:9)
    at getDiagnostics2 (h:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\typescript.js:81901:16)
    at Object.getEmitResolver (h:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\typescript.js:45860:7)
    at h:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\typescript.js:117098:43
[Info  - 10:08:30 AM] Connection to server got closed. Server will restart.
true
h:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\typescript.js:82757
      Debug.assert(!compilerOptions.verbatimModuleSyntax);
            ^

Error: Debug Failure. False expression.
    at isReferencedAliasDeclaration (h:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\typescript.js:82757:13)
    at canConvertImportDeclarationToTypeOnly (h:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\typescript.js:81296:177)
    at checkImportsForTypeOnlyConversion (h:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\typescript.js:81311:13)
    at checkSourceFileWorker (h:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\typescript.js:81874:11)
    at checkSourceFile (h:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\typescript.js:81822:7)
    at checkSourceFileWithEagerDiagnostics (h:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\typescript.js:81916:7)
    at getDiagnosticsWorker (h:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\typescript.js:81924:9)
    at getDiagnostics2 (h:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\typescript.js:81901:16)
    at Object.getEmitResolver (h:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\typescript.js:45860:7)
    at h:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\typescript.js:117098:43
[Info  - 10:08:34 AM] Connection to server got closed. Server will restart.
true
h:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\typescript.js:82757
      Debug.assert(!compilerOptions.verbatimModuleSyntax);
            ^

Error: Debug Failure. False expression.
    at isReferencedAliasDeclaration (h:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\typescript.js:82757:13)
    at canConvertImportDeclarationToTypeOnly (h:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\typescript.js:81296:177)
    at checkImportsForTypeOnlyConversion (h:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\typescript.js:81311:13)
    at checkSourceFileWorker (h:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\typescript.js:81874:11)
    at checkSourceFile (h:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\typescript.js:81822:7)
    at checkSourceFileWithEagerDiagnostics (h:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\typescript.js:81916:7)
    at getDiagnosticsWorker (h:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\typescript.js:81924:9)
    at getDiagnostics2 (h:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\typescript.js:81901:16)
    at Object.getEmitResolver (h:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\typescript.js:45860:7)
    at h:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\typescript.js:117098:43
[Info  - 10:08:39 AM] Connection to server got closed. Server will restart.
true
h:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\typescript.js:82757
      Debug.assert(!compilerOptions.verbatimModuleSyntax);
            ^

Error: Debug Failure. False expression.
    at isReferencedAliasDeclaration (h:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\typescript.js:82757:13)
    at canConvertImportDeclarationToTypeOnly (h:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\typescript.js:81296:177)
    at checkImportsForTypeOnlyConversion (h:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\typescript.js:81311:13)
    at checkSourceFileWorker (h:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\typescript.js:81874:11)
    at checkSourceFile (h:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\typescript.js:81822:7)
    at checkSourceFileWithEagerDiagnostics (h:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\typescript.js:81916:7)
    at getDiagnosticsWorker (h:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\typescript.js:81924:9)
    at getDiagnostics2 (h:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\typescript.js:81901:16)
    at Object.getEmitResolver (h:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\typescript.js:45860:7)
    at h:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\typescript.js:117098:43
[Info  - 10:08:43 AM] Connection to server got closed. Server will restart.
true
h:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\typescript.js:82757
      Debug.assert(!compilerOptions.verbatimModuleSyntax);
            ^

Error: Debug Failure. False expression.
    at isReferencedAliasDeclaration (h:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\typescript.js:82757:13)
    at canConvertImportDeclarationToTypeOnly (h:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\typescript.js:81296:177)
    at checkImportsForTypeOnlyConversion (h:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\typescript.js:81311:13)
    at checkSourceFileWorker (h:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\typescript.js:81874:11)
    at checkSourceFile (h:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\typescript.js:81822:7)
    at checkSourceFileWithEagerDiagnostics (h:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\typescript.js:81916:7)
    at getDiagnosticsWorker (h:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\typescript.js:81924:9)
    at getDiagnostics2 (h:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\typescript.js:81901:16)
    at Object.getEmitResolver (h:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\typescript.js:45860:7)
    at h:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\typescript.js:117098:43
[Error - 10:08:48 AM] The Vue Semantic Server server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
```

**Comment by leegee** [comment]
One of my components suffered a name change: everything but the name of the file changed. 
When I corrected the name of the file, and restarted VSC, the error seemed to disappear.
Now I realise just how much **** your extension saves me, I'd like to buy you a beer!

**Comment by leegee** [comment]
![image](https://user-images.githubusercontent.com/512816/229458726-e9341b00-c209-4478-9209-ff2498d183cc.png)

It's back for no discernible reason.

**Comment by leegee** [comment]
I got the same error with both the release and pre-release branches. 
My tsconfig `"extends": "@vue/tsconfig/tsconfig.node.json"`, but I've added the suggested option and will close this ticket if the error doesn't return in a few hours.
Thanks!

**Comment by leegee** [comment]
Seems to have worked, thanks! 
Can't find the buy-me-a-coffee link, only links to sponsorships, which I can't afford from Eastern Europe

**Comment by leegee** [comment]
Sorry, I was wrong. After restarting VSC, the error persists.

**Comment by leegee** [comment]
Turns out Vue3 CLI-supplied "dev server" didn't pick up the below, which the CLI-supplied `type-test` did, so I guess this ticket should be elsewhere?

```
> @x/client@1.0.10 type-check
> vue-tsc --noEmit -p tsconfig.vitest.json --composite false

S:\src\x-x\node_modules\typescript\lib\tsserverlibrary.js:116826
        throw e;
        ^

Error: Debug Failure. False expression.
    at isReferencedAliasDeclaration (S:\src\x-x\node_modules\typescript\lib\tsserverlibrary.js:82767:13)
    at canConvertImportDeclarationToTypeOnly (S:\src\x-x\node_modules\typescript\lib\tsserverlibrary.js:81306:177)
    at checkImportsForTypeOnlyConversion (S:\src\x-x\node_modules\typescript\lib\tsserverlibrary.js:81321:13)
    at checkSourceFileWorker (S:\src\x-x\node_modules\typescript\lib\tsserverlibrary.js:81884:11)
    at checkSourceFile (S:\src\x-x\node_modules\typescript\lib\tsserverlibrary.js:81832:7)
    at checkSourceFileWithEagerDiagnostics (S:\src\x-x\node_modules\typescript\lib\tsserverlibrary.js:81926:7)
    at getDiagnosticsWorker (S:\src\x-x\node_modules\typescript\lib\tsserverlibrary.js:81934:9)
    at Object.getDiagnostics2 [as getDiagnostics] (S:\src\x-x\node_modules\typescript\lib\tsserverlibrary.js:81911:16)
    at S:\src\x-x\node_modules\typescript\lib\tsserverlibrary.js:116851:78
    at runWithCancellationToken (S:\src\x-x\node_modules\typescript\lib\tsserverlibrary.js:116821:16)

Node.js v18.4.0
```

**Comment by johnsoncodehk** [comment]
It looks like a bug inside TS, if you still have this problem, please provide a repro case.
