### ISSUE TITLE
Error running `vue-tsc` @ `v1.7.8`

### ISSUE THREAD

**Issue by Jazcash** [vuejs/language-tools#3230]
```
$ npx vue-tsc --noEmit -p tsconfig.web.json

C:\Users\me\Repos\bar-lobby\node_modules\@vue\language-core\out\generators\template.js:221
                        tagOffsetsMap[tag] ??= [];
                                           ^^^

SyntaxError: Unexpected token '??='
    at wrapSafe (internal/modules/cjs/loader.js:1001:16)
    at Module._compile (internal/modules/cjs/loader.js:1049:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (C:\Users\jaspe\Repos\bar-lobby\node_modules\@vue\language-core\out\index.js:18:14)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
```

`tsconfig.web.json`:
```json
{
  "extends": "@electron-toolkit/tsconfig/tsconfig.web.json",
  "include": [
    "src/renderer/**/*", "src/common/**/*"
  ],
  "compilerOptions": {
    "composite": true,
    "baseUrl": ".",
    "paths": {
      "@/*": ["src/renderer/*"],
      "$/*": ["src/common/*"],
      "jaz-ts-utils": ["node_modules/jaz-ts-utils"]
    },
    "types": ["vite/client"],
    "noEmit": true,
    "downlevelIteration": true,
    "noUnusedParameters": false,
    "noUnusedLocals": false,
    "noImplicitOverride": true,
    "allowJs": true
  }
}
```

`deps:`
```
    "typescript": "^5.0.4",
    "vue": "^3.3.4",
    "vue-tsc": "^1.7.8",
```

Any ideas?

**Comment by lucasavila00** [comment]
What version of NodeJS are you using?

I assume it's node 14, which doesn't support the `??=` syntax.

```
Welcome to Node.js v14.21.3.
Type ".help" for more information.
> a ??= 1
a ??= 1
  ^^^
``` 

```
Welcome to Node.js v18.16.0.
Type ".help" for more information.
> let a
undefined
> a ??= 1
1
```

**Comment by Jazcash** [comment]
Ah yeah, that'll be it - using node 14.21.2. Is that now an unsupported version by this package?

**Comment by so1ve** [comment]
Yes, please use node 16 since v14 has reached EOL
