### ISSUE TITLE
The Vue Semantic Server server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.

### ISSUE THREAD

**Issue by sakib412** [vuejs/language-tools#3310]
```
RangeError: Maximum call stack size exceeded
    at RegExp.test (<anonymous>)
    at w (/home/user/.vscode/extensions/vue.volar-1.8.0/dist/server.js:76:39147)
    at w (/home/user/.vscode/extensions/vue.volar-1.8.0/dist/server.js:76:39175)
    at w (/home/user/.vscode/extensions/vue.volar-1.8.0/dist/server.js:76:39175)
    at w (/home/user/.vscode/extensions/vue.volar-1.8.0/dist/server.js:76:39175)
    at w (/home/user/.vscode/extensions/vue.volar-1.8.0/dist/server.js:76:39175)
    at w (/home/user/.vscode/extensions/vue.volar-1.8.0/dist/server.js:76:39175)
    at w (/home/user/.vscode/extensions/vue.volar-1.8.0/dist/server.js:76:39175)
    at w (/home/user/.vscode/extensions/vue.volar-1.8.0/dist/server.js:76:39175)
    at w (/home/user/.vscode/extensions/vue.volar-1.8.0/dist/server.js:76:39175)
[Error - 12:58:42 PM] The Vue Semantic Server server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
```

I tried to uninstall and install it again.

**Comment by johnsoncodehk** [comment]
Duplicate of #3282
