### ISSUE TITLE
1.8.2 crashes in vsCode

### ISSUE THREAD

**Issue by ToyYan** [vuejs/language-tools#3332]
![image](https://github.com/vuejs/language-tools/assets/508968/622d26bc-0b40-45db-8f3e-cd9efbf6ae4f)

>  
Err 181   [15:53:30.649] Exception on executing command {
  "seq": 2,
  "type": "request",
  "command": "updateOpen",
  "arguments": {
    "changedFiles": [],
    "closedFiles": [],
    "openFiles": [
      {
        "file": "/Users/ysj/seedata/guotai/guotai-fe/src/common/useUeData.ts",
        "fileContent": "import ue4Provide from \"@/ue4/ue4Provide\";\nue4Provide.on('requestData', data: any) {\n  console.log(data);\n}",
        "projectRootPath": "/Users/ysj/seedata/guotai/guotai-fe",
        "scriptKindName": "TS"
      },
      {
        "file": "/Users/ysj/seedata/guotai/guotai-be/src/api/cmdb/cmdb.controller.ts",
        "fileContent": "import { Controller, Get, Query } from '@nestjs/common';\nimport { CmdbService } from './cmdb.service';\n\n@Controller('cmdb')\nexport class CmdbController {\n  constructor(private readonly cmdbService: CmdbService) {}\n  @Get()\n  index() {\n    return 'cmdb';\n  }\n\n  @Get('getServer')\n  async getServer(@Query('id') id) {\n    const data = await this.cmdbService.findOne(id);\n    return data;\n  }\n\n  @Get('getServerList')\n  async getServerList(\n    @Query('buildId') buildId: string,\n    @Query('floorNum') floorNum: string,\n  ) {\n    const data = await this.cmdbService.findListByJGBH(\n      `DC-${buildId}-L0${floorNum}-ITBCR0-`,\n    );\n    return data;\n  }\n}\n",
        "projectRootPath": "/Users/ysj/seedata/guotai/guotai-be",
        "scriptKindName": "TS"
      }
    ]
  }
}:

    Debug Failure. False expression.

    Error: Debug Failure. False expression.
        at TextStorage.getFileTextAndSize (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:173060:15)
        at TextStorage.reloadWithFileText (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:172983:104)
        at TextStorage.getOrLoadText (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:173094:12)
        at TextStorage.tryUseScriptVersionCache (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:173080:12)
        at TextStorage.getSnapshot (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:173011:24)
        at ScriptInfo.getLatestVersion (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:173317:22)
        at ConfiguredProject2.getScriptVersion (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:173801:25)
        at updateScript (/Users/ysj/.vscode/extensions/vue.vscode-typescript-vue-plugin-1.8.2/dist/index.js:51109:45)
        at resolveModuleName (/Users/ysj/.vscode/extensions/vue.vscode-typescript-vue-plugin-1.8.2/dist/index.js:51101:26)
        at /Users/ysj/.vscode/extensions/vue.vscode-typescript-vue-plugin-1.8.2/dist/index.js:51050:22
        at Array.map (<anonymous>)
        at languageServiceHost.resolveModuleNameLiterals (/Users/ysj/.vscode/extensions/vue.vscode-typescript-vue-plugin-1.8.2/dist/index.js:51048:30)
        at resolveModuleNamesWorker (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:118955:20)
        at resolveModuleNamesReusingOldState (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:119051:14)
        at processImportedModules (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:120623:27)
        at findSourceFileWorker (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:120353:7)
        at findSourceFile (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:120218:20)
        at processImportedModules (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:120647:11)
        at findSourceFileWorker (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:120353:7)
        at findSourceFile (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:120218:20)
        at processImportedModules (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:120647:11)
        at findSourceFileWorker (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:120353:7)
        at findSourceFile (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:120218:20)
        at processImportedModules (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:120647:11)
        at findSourceFileWorker (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:120353:7)
        at findSourceFile (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:120218:20)
        at processImportedModules (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:120647:11)
        at findSourceFileWorker (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:120353:7)
        at findSourceFile (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:120218:20)
        at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:120167:22
        at getSourceFileFromReferenceWorker (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:120136:26)
        at processSourceFile (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:120165:5)
        at processRootFile (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:119962:5)
        at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:118717:41
        at forEach (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:2325:22)
        at createProgram (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:118717:5)
        at synchronizeHostData (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:141865:15)
        at Object.getProgram (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:141939:5)
        at ConfiguredProject2.updateGraphWorker (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:174510:41)
        at ConfiguredProject2.updateGraph (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:174362:32)
        at ConfiguredProject2.updateGraph (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:175615:24)
        at updateProjectIfDirty (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:176068:35)
        at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:178332:15
        at callback (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:176017:21)
        at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:175996:57
        at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:176031:20
        at forEach (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:2325:22)
        at forEachResolvedProjectReferenceProjectWorker (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:176022:10)
        at forEachResolvedProjectReferenceProject (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:175993:22)
        at _ProjectService.assignProjectToOpenedScriptInfo (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:178328:11)
        at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:178600:64
        at flatMap (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:2573:17)
        at _ProjectService.applyChangesInOpenFiles (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:178600:24)
        at updateOpen (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:179780:29)
        at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:182353:69
        at IpcIOSession.executeWithRequestId (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:182345:14)
        at IpcIOSession.executeCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:182353:29)
        at IpcIOSession.onMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:182395:51)
        at process.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:183975:14)
        at process.emit (node:events:513:28)
        at emit (node:internal/child_process:967:14)
        at process.processTicksAndRejections (node:internal/process/task_queues:84:21)
Info 182  [15:53:30.649] response:
    {"seq":0,"type":"response","command":"updateOpen","request_seq":2,"success":false,"performanceData":{"updateGraphDurationMs":21.608749866485596},"message":"Error processing request. Debug Failure. False expression.\nError: Debug Failure. False expression.\n    at TextStorage.getFileTextAndSize (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:173060:15)\n    at TextStorage.reloadWithFileText (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:172983:104)\n    at TextStorage.getOrLoadText (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:173094:12)\n    at TextStorage.tryUseScriptVersionCache (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:173080:12)\n    at TextStorage.getSnapshot (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:173011:24)\n    at ScriptInfo.getLatestVersion (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:173317:22)\n    at ConfiguredProject2.getScriptVersion (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:173801:25)\n    at updateScript (/Users/ysj/.vscode/extensions/vue.vscode-typescript-vue-plugin-1.8.2/dist/index.js:51109:45)\n    at resolveModuleName (/Users/ysj/.vscode/extensions/vue.vscode-typescript-vue-plugin-1.8.2/dist/index.js:51101:26)\n    at /Users/ysj/.vscode/extensions/vue.vscode-typescript-vue-plugin-1.8.2/dist/index.js:51050:22\n    at Array.map (<anonymous>)\n    at languageServiceHost.resolveModuleNameLiterals (/Users/ysj/.vscode/extensions/vue.vscode-typescript-vue-plugin-1.8.2/dist/index.js:51048:30)\n    at resolveModuleNamesWorker (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:118955:20)\n    at resolveModuleNamesReusingOldState (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:119051:14)\n    at processImportedModules (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:120623:27)\n    at findSourceFileWorker (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:120353:7)\n    at findSourceFile (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:120218:20)\n    at processImportedModules (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:120647:11)\n    at findSourceFileWorker (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:120353:7)\n    at findSourceFile (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:120218:20)\n    at processImportedModules (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:120647:11)\n    at findSourceFileWorker (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:120353:7)\n    at findSourceFile (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:120218:20)\n    at processImportedModules (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:120647:11)\n    at findSourceFileWorker (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:120353:7)\n    at findSourceFile (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:120218:20)\n    at processImportedModules (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:120647:11)\n    at findSourceFileWorker (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:120353:7)\n    at findSourceFile (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:120218:20)\n    at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:120167:22\n    at getSourceFileFromReferenceWorker (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:120136:26)\n    at processSourceFile (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:120165:5)\n    at processRootFile (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:119962:5)\n    at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:118717:41\n    at forEach (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:2325:22)\n    at createProgram (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:118717:5)\n    at synchronizeHostData (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:141865:15)\n    at Object.getProgram (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:141939:5)\n    at ConfiguredProject2.updateGraphWorker (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:174510:41)\n    at ConfiguredProject2.updateGraph (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:174362:32)\n    at ConfiguredProject2.updateGraph (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:175615:24)\n    at updateProjectIfDirty (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:176068:35)\n    at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:178332:15\n    at callback (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:176017:21)\n    at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:175996:57\n    at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:176031:20\n    at forEach (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:2325:22)\n    at forEachResolvedProjectReferenceProjectWorker (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:176022:10)\n    at forEachResolvedProjectReferenceProject (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:175993:22)\n    at _ProjectService.assignProjectToOpenedScriptInfo (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:178328:11)\n    at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:178600:64\n    at flatMap (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:2573:17)\n    at _ProjectService.applyChangesInOpenFiles (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:178600:24)\n    at updateOpen (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:179780:29)\n    at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:182353:69\n    at IpcIOSession.executeWithRequestId (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:182345:14)\n    at IpcIOSession.executeCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:182353:29)\n    at IpcIOSession.onMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:182395:51)\n    at process.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:183975:14)\n    at process.emit (node:events:513:28)\n    at emit (node:internal/child_process:967:14)\n    at process.processTicksAndRejections (node:internal/process/task_queues:84:21)"}
Info 183  [15:53:30.650] request:
    {
      "seq": 4,
      "type": "request",
      "command": "geterr",
      "arguments": {
        "delay": 0,
        "files": [
          "/Users/ysj/seedata/guotai/guotai-fe/src/common/useUeData.ts",
          "/Users/ysj/seedata/guotai/guotai-be/src/api/cmdb/cmdb.controller.ts"
        ]
      }
    }

**Comment by marktlinn** [comment]
I've had the same issue, Have installed the previous version on VSCode and it works fine, so must be due to the most recent update.

**Comment by meanspa** [comment]
Also crashing for me, although with some differences:
- I'm not using Typescript
- The error Message: `The Vue Semantic Server server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.`
- Output: 
`TypeError: Cannot read properties of undefined (reading 'package.json')
    at Object.h [as fileExists] (/Users/myusername/.vscode/extensions/vue.volar-1.8.2/dist/server.js:77:1416)
    at Proxy.x (/Users/myusername/.vscode/extensions/vue.volar-1.8.2/dist/server.js:76:37698)
    at Object.fileExists (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:139762:40)
    at host.fileExists (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:116036:43)
    at Object.fileExists (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:119567:30)
    at getPackageJsonInfo (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:40352:33)
    at loadNodeModuleFromDirectory (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:40184:47)
    at nodeLoadModuleByRelativeName (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:40058:14)
    at tryResolve (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:39991:27)
    at nodeModuleNameResolverWorker (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:39925:38)`

**Comment by johnsoncodehk** [comment]
@ToyYan look to the source code that reports this error, you may have a vue file that file size over `maxFileSize` (4 * 1024 * 1024 = 4 MB).

https://github.com/microsoft/TypeScript/blob/218d380289aa785b2263d9b8e728503d93f5933b/src/server/scriptInfo.ts#L272-L275

Is this the correct situation to you? Can you add a log at `/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:173060:15` to see if it's a normal file that's causing the crash?

**Comment by johnsoncodehk** [comment]
@meanspa It seems to crash at https://github.com/volarjs/volar.js/blob/c28b1b3fc725f38d335f4341179678c78828528f/packages/typescript/src/sys.ts#L177, I have no idea why it would crash for now, but this is a different problem, could you open a new issue?

**Comment by meanspa** [comment]
Sure thing, here's the new issue: https://github.com/vuejs/language-tools/issues/3336

**Comment by eiqli-zhao** [comment]
I also encountered the same problem.
