### ISSUE TITLE
EACCESS crashes the server

### ISSUE THREAD

**Issue by dscottboggs** [vuejs/language-tools#3511]
My project directory contains a directory which is not readable (owned by a different user). The existence of this directory crashes the server.

## Steps to reproduce

- Install VS Cod(e|ium).
- Install the Vue.volar plugin.
- Open a Vue project
- `sudo mkdir problem`

## Expected behavior
The plugin ignores this error, perhaps emitting a warning, and continues to start. Alternatively, the plugin is configurable in some way to ignore certain files or directories within a project directory.

## Error Logs

```
node:fs:1442
  handleErrorFromBinding(ctx);
  ^

Error: EACCES: permission denied, scandir '/home/scott/src/kalkutago/db.mount'
    at Object.readdirSync (node:fs:1442:3)
    at t.readdirSync (node:electron/js2c/asar_bundle:2:10837)
    at Object.readDirectory (/nix/store/nrwr1bw6hdg4k34can4y4qig73x9fi98-vscode-extension-Vue-volar-1.7.11/share/vscode/extensions/Vue.volar/dist/server.js:77:33947)
    at Object.readDirectory (/nix/store/nrwr1bw6hdg4k34can4y4qig73x9fi98-vscode-extension-Vue-volar-1.7.11/share/vscode/extensions/Vue.volar/dist/server.js:77:30107)
    at b (/nix/store/nrwr1bw6hdg4k34can4y4qig73x9fi98-vscode-extension-Vue-volar-1.7.11/share/vscode/extensions/Vue.volar/dist/server.js:77:3184)
    at /nix/store/nrwr1bw6hdg4k34can4y4qig73x9fi98-vscode-extension-Vue-volar-1.7.11/share/vscode/extensions/Vue.volar/dist/server.js:77:1942
    at w (/nix/store/nrwr1bw6hdg4k34can4y4qig73x9fi98-vscode-extension-Vue-volar-1.7.11/share/vscode/extensions/Vue.volar/dist/server.js:76:38771)
    at w (/nix/store/nrwr1bw6hdg4k34can4y4qig73x9fi98-vscode-extension-Vue-volar-1.7.11/share/vscode/extensions/Vue.volar/dist/server.js:76:39220)
    at Aoe (/nix/store/nrwr1bw6hdg4k34can4y4qig73x9fi98-vscode-extension-Vue-volar-1.7.11/share/vscode/extensions/Vue.volar/dist/server.js:76:38625)
    at Proxy.w (/nix/store/nrwr1bw6hdg4k34can4y4qig73x9fi98-vscode-extension-Vue-volar-1.7.11/share/vscode/extensions/Vue.volar/dist/server.js:77:1885) {
  errno: -13,
  syscall: 'scandir',
  code: 'EACCES',
  path: '/home/scott/src/kalkutago/db.mount'
}
```

**Comment by so1ve** [comment]
You should fire it in https://github.com/volarjs/volar.js
