### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'package.json')

### ISSUE THREAD

**Issue by datyin** [vuejs/language-tools#3580]
I got back to an few months old project that was working fine and now the The Vue Semantic Server keeps crashing.

What i've tried so far is:
- Update dependencies to latest version (Extensions are up to date)
- Tried to use TypeScript Vue Plugin (Volar) and Built-In Typescript (both fail with vue files)

`tsconfig.json`
```json
{
  "compilerOptions": {
    "target": "ESNext",
    "useDefineForClassFields": true,
    "module": "ESNext",
    "lib": ["ESNext", "DOM", "DOM.Iterable"],
    "skipLibCheck": true,
    "allowImportingTsExtensions": true,
    "allowSyntheticDefaultImports": true,

    /* Bundler mode */
    "moduleResolution": "Bundler",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "preserve",

    /* Linting */
    "strict": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "noFallthroughCasesInSwitch": true
  },
  "include": [
    "src/**/*.ts",
    "src/**/*.tsx",
    "src/**/*.vue"
  ]
}
```

`package.json`
```json
{
  "private": true,
  "name": "bat-spfx-webpart",
  "version": "1.4.0",
  "author": {
    "name": "bat-groupware GmbH",
    "email": "office@bat.at",
    "url": "https://www.bat.at/"
  },
  "scripts": {
    "build": "gulp clean && gulp bundle && gulp package-solution --ship",
    "build:vite": "vite build",
    "package": "gulp package-solution --ship",
    "serve": "gulp serve --nobrowser",
    "clean": "gulp clean",
    "test": "gulp test"
  },
  "dependencies": {
    "@bat/attributes-core": "0.0.7",
    "@bat/attributes-localization": "1.0.1",
    "@bat/attributes-spfx": "0.0.9",
    "@bat/attributes-vue": "0.0.6",
    "@bat/core": "1.0.8",
    "@bat/naive-ui": "0.1.4",
    "@bat/spfx": "1.0.3",
    "@bat/validators": "1.0.2",
    "@microsoft/sp-component-base": "1.18.0",
    "@microsoft/sp-core-library": "1.18.0",
    "@microsoft/sp-webpart-base": "1.18.0",
    "@pnp/sp": "3.18.0",
    "naive-ui": "2.34.4",
    "vue": "3.3.4",
    "xlsx": "0.18.5"
  },
  "devDependencies": {
    "@bat/eslint-config-vue": "1.0.5",
    "@bat/gulp-plugin-vite": "1.0.1",
    "@bat/tsconfig-vue": "1.0.0",
    "@bat/types": "1.0.3",
    "@microsoft/rush-stack-compiler-4.7": "0.1.0",
    "@microsoft/sp-build-web": "1.18.0",
    "@total-typescript/ts-reset": "0.5.1",
    "@types/node": "20.6.3",
    "@types/webpack-env": "1.18.1",
    "@vitejs/plugin-vue": "4.3.4",
    "eslint": "8.49.0",
    "gulp": "4.0.2",
    "typescript": "5.2.2",
    "vite": "4.4.9"
  },
  "pnpm": {
    "overrides": {
      "@microsoft/load-themed-styles": "2.0.29"
    },
    "peerDependencyRules": {
      "allowAny": [
        "@microsoft/microsoft-graph-client",
        "@microsoft/load-themed-styles"
      ]
    }
  }
}

```

```
TypeError: Cannot read properties of undefined (reading 'package.json')
    at g (c:\Users\jovej\.vscode\extensions\vue.volar-1.8.13\dist\server.js:77:1578)
    at Object.h [as fileExists] (c:\Users\jovej\.vscode\extensions\vue.volar-1.8.13\dist\server.js:77:1167)
    at Object.y [as fileExists] (c:\Users\jovej\.vscode\extensions\vue.volar-1.8.13\dist\server.js:76:36331)
    at getPackageJsonInfo (E:\BAT Projects\BATWebPart\node_modules\.pnpm\typescript@5.2.2\node_modules\typescript\lib\typescript.js:40692:33)
    at loadNodeModuleFromDirectory (E:\BAT Projects\BATWebPart\node_modules\.pnpm\typescript@5.2.2\node_modules\typescript\lib\typescript.js:40505:47)
    at nodeLoadModuleByRelativeName (E:\BAT Projects\BATWebPart\node_modules\.pnpm\typescript@5.2.2\node_modules\typescript\lib\typescript.js:40379:14)
    at tryResolve (E:\BAT Projects\BATWebPart\node_modules\.pnpm\typescript@5.2.2\node_modules\typescript\lib\typescript.js:40312:27)
    at nodeModuleNameResolverWorker (E:\BAT Projects\BATWebPart\node_modules\.pnpm\typescript@5.2.2\node_modules\typescript\lib\typescript.js:40248:16)
    at bundlerModuleNameResolver (E:\BAT Projects\BATWebPart\node_modules\.pnpm\typescript@5.2.2\node_modules\typescript\lib\typescript.js:40176:12)
    at Object.resolveModuleName (E:\BAT Projects\BATWebPart\node_modules\.pnpm\typescript@5.2.2\node_modules\typescript\lib\typescript.js:39969:20)

Node.js v18.15.0
[Error - 7:11:50 PM] The Vue Semantic Server server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
```

**Comment by datyin** [comment]
P.S: setting "moduleResolution": "Node16" / "NodeNext" at least shows errors, other options gives 0 types/errors

**Comment by johnsoncodehk** [comment]
It should fixed by https://github.com/volarjs/volar.js/pull/59.
