### ISSUE TITLE
volar代码提示不生效

### ISSUE THREAD

**Issue by chengxg** [vuejs/language-tools#3851]
vscode版本:
  版本: 1.85.1
  提交: 0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2
  日期: 2023-12-13T09:49:37.021Z
  Electron: 25.9.7
  ElectronBuildId: 25551756
  Chromium: 114.0.5735.289
  Node.js: 18.15.0
  V8: 11.4.183.29-electron.0
  OS: Windows_NT x64 10.0.22621

volar版本: v1.8.27

问题描述: vue文件没有任何代码提示, crtl+鼠标左键也不能跳转到变量定义

插件运行时错误:
Request vue/detectTagCasing failed with message: Cannot read properties of undefined (reading 'traceResolution')

![image](https://github.com/vuejs/language-tools/assets/21291106/aedfa509-a99c-4416-8208-ad76f7f724e9)

**Comment by so1ve** [comment]
Do you have any reproduction?

**Comment by Hoody123** [comment]
same problem
![image](https://github.com/vuejs/language-tools/assets/11456499/fac9e691-dacf-4122-9102-261770ce6ab8)
![image](https://github.com/vuejs/language-tools/assets/11456499/f8fab098-1628-4f5c-b82f-1f714fe33dc9)
![image](https://github.com/vuejs/language-tools/assets/11456499/cc558390-95b1-4256-8ba7-8f2f8faca632)
![image](https://github.com/vuejs/language-tools/assets/11456499/f36b4e4e-2931-4521-9eb0-084c076c04b2)

As I updated my vsCode, all vue file with Vue3.x and .ts file cannot highlight any syntax.

**Comment by WangJincheng4869** [comment]
> Do you have any reproduction?

我也是卡的起飞，有没有什么配置秘籍啊，代码提示十多秒都出不来，只能反复重启 Volar。

**Comment by Roywhite** [comment]
workbench.desktop.main.js:sourcemap:2004 
Error: Pending response rejected since connection got disposed
    at Object.dispose (c:\Users\Administrator\.vscode\extensions\vue.volar-1.8.27\dist\client.js:31:4574)
    at Object.dispose (c:\Users\Administrator\.vscode\extensions\vue.volar-1.8.27\dist\client.js:44:9744)
    at p.handleConnectionClosed (c:\Users\Administrator\.vscode\extensions\vue.volar-1.8.27\dist\client.js:41:12801)
    at p.handleConnectionClosed (c:\Users\Administrator\.vscode\extensions\vue.volar-1.8.27\dist\client.js:44:38817)
    at t (c:\Users\Administrator\.vscode\extensions\vue.volar-1.8.27\dist\client.js:41:12417)
    at zc.invoke (c:\Users\Administrator\.vscode\extensions\vue.volar-1.8.27\dist\client.js:1:11643)
    at n.fire (c:\Users\Administrator\.vscode\extensions\vue.volar-1.8.27\dist\client.js:1:12412)
    at It (c:\Users\Administrator\.vscode\extensions\vue.volar-1.8.27\dist\client.js:5:5912)
    at zc.invoke (c:\Users\Administrator\.vscode\extensions\vue.volar-1.8.27\dist\client.js:1:11643)
    at n.fire (c:\Users\Administrator\.vscode\extensions\vue.volar-1.8.27\dist\client.js:1:12412)
    at bu.fireClose (c:\Users\Administrator\.vscode\extensions\vue.volar-1.8.27\dist\client.js:1:16786)
    at ChildProcess.<anonymous> (c:\Users\Administrator\.vscode\extensions\vue.volar-1.8.27\dist\client.js:31:16294)
    at ChildProcess.emit (node:events:526:35)
    at maybeClose (node:internal/child_process:1091:16)
    at Process.onexit (node:internal/child_process:302:5)

**Comment by davidmatter** [comment]
Closing this one as many things have changed since 2.x. Feel free to create a new issue with a minimal reproduction if you're still having issues, thanks!
