### ISSUE TITLE
volar+nuxtjs无代码提示

### ISSUE THREAD

**Issue by Roywhite** [vuejs/language-tools#3904]
版本: 1.86.0 (user setup)
提交: 05047486b6df5eb8d44b2ecd70ea3bdf775fd937
日期: 2024-01-31T10:28:19.990Z
Electron: 27.2.3
ElectronBuildId: 26495564
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Windows_NT x64 10.0.19045

volar插件版本：v1.8.27
问题描述：在使用volar搭配nuxtjs时，完全没有代码提示

扩展宿主报错信息：
`[error] Error: Pending response rejected since connection got disposed
    at Object.dispose (c:\Users\Administrator\.vscode\extensions\vue.volar-1.8.27\dist\client.js:31:4574)
    at Object.dispose (c:\Users\Administrator\.vscode\extensions\vue.volar-1.8.27\dist\client.js:44:9744)
    at p.handleConnectionClosed (c:\Users\Administrator\.vscode\extensions\vue.volar-1.8.27\dist\client.js:41:12801)
    at p.handleConnectionClosed (c:\Users\Administrator\.vscode\extensions\vue.volar-1.8.27\dist\client.js:44:38817)
    at t (c:\Users\Administrator\.vscode\extensions\vue.volar-1.8.27\dist\client.js:41:12417)
    at zc.invoke (c:\Users\Administrator\.vscode\extensions\vue.volar-1.8.27\dist\client.js:1:11643)
    at n.fire (c:\Users\Administrator\.vscode\extensions\vue.volar-1.8.27\dist\client.js:1:12412)
    at It (c:\Users\Administrator\.vscode\extensions\vue.volar-1.8.27\dist\client.js:5:5912)
    at zc.invoke (c:\Users\Administrator\.vscode\extensions\vue.volar-1.8.27\dist\client.js:1:11643)
    at n.fire (c:\Users\Administrator\.vscode\extensions\vue.volar-1.8.27\dist\client.js:1:12412)
    at bu.fireClose (c:\Users\Administrator\.vscode\extensions\vue.volar-1.8.27\dist\client.js:1:16786)
    at ChildProcess.<anonymous> (c:\Users\Administrator\.vscode\extensions\vue.volar-1.8.27\dist\client.js:31:16294)
    at ChildProcess.emit (node:events:526:35)
    at maybeClose (node:internal/child_process:1091:16)
    at Process.onexit (node:internal/child_process:302:5)`

插件页报错信息：
![image](https://github.com/vuejs/language-tools/assets/42577687/cab72daa-643b-41f4-b7e6-3800cbf6d6f0)

**Comment by davidmatter** [comment]
Please check if this issue has been resolved in version 2.x. If not, feel free to create a new one.
