### ISSUE TITLE
Neovim Volar LSP broken for 2.0.7

### ISSUE THREAD

**Issue by ASoldo** [vuejs/language-tools#4159]
Hi, I just noticed that when I open any of my projects new or old I don't have any TS/JS/Vue completions even tho it shows as running. But I am not able to hover, jump to definitions, etc... anybody know why and how to fix it?

Thank you!

**Comment by ASoldo** [comment]
I solved it with this snippet for 2.x version in my init.lua:
```lua
local lspconfig = require('lspconfig')
  lspconfig.volar.setup {
    filetypes = { 'typescript', 'javascript', 'javascriptreact', 'typescriptreact', 'vue' },
    init_options = {
      vue = {
        hybridMode = false,
      },
    },
  }
  ```
  I was not aware of upgrade to 2.x and my problem is fixed by following docs for nvim integration.

**Comment by johnsoncodehk** [comment]
2.0 was recommanded to use with `@vue/typescript-plugin`, you can the "How to configure vue language server with neovim and lsp?" section at: https://github.com/vuejs/language-tools#community-integration

Or the full discuss: #3925

**Comment by CofCat456** [comment]
If you could share your nvim config, it would be better to solve your problem.

**Comment by ASoldo** [comment]
> If you could share your nvim config, it would be better to solve your problem.

```lua
return {
  -- Configure AstroNvim updates
  updater = {
    remote = "origin",     -- remote to use
    channel = "stable",    -- "stable" or "nightly"
    version = "latest",    -- "latest", tag name, or regex search like "v1.*" to only do updates before v2 (STABLE ONLY)
    branch = "nightly",    -- branch name (NIGHTLY ONLY)
    commit = nil,          -- commit hash (NIGHTLY ONLY)
    pin_plugins = nil,     -- nil, true, false (nil will pin plugins on stable only)
    skip_prompts = false,  -- skip prompts about breaking changes
    show_changelog = true, -- show the changelog after performing an update
    auto_quit = false,     -- automatically quit the current session after a successful update
    remotes = {            -- easily add new remotes to track
      --   ["remote_name"] = "https://remote_url.come/repo.git", -- full remote url
      --   ["remote2"] = "github_user/repo", -- GitHub user/repo shortcut,
      --   ["remote3"] = "github_user", -- GitHub user assume AstroNvim fork
    },
  },
  -- Set colorscheme to use
  colorscheme = "astrodark",
  -- Diagnostics configuration (for vim.diagnostics.config({...})) when diagnostics are on
  diagnostics = {
    virtual_text = true,
    underline = true,
  },
  lsp = {
    -- customize lsp formatting options
    formatting = {
      -- control auto formatting on save
      format_on_save = {
        enabled = true,     -- enable or disable format on save globally
        allow_filetypes = { -- enable format on save for specified filetypes only
          -- "go",
        },
        ignore_filetypes = { -- disable format on save for specified filetypes
          -- "python",
        },
      },
      disabled = { -- disable formatting capabilities for the listed language servers
        -- "sumneko_lua",
      },
      timeout_ms = 1000, -- default format timeout
      -- filter = function(client) -- fully override the default formatting function
      --   return true
      -- end
    },
    -- enable servers that you already have installed without mason
    servers = {
      -- "pyright"
    },
  },
  -- Configure require("lazy").setup() options
  lazy = {
    defaults = { lazy = true },
    performance = {
      rtp = {
        -- customize default disabled vim plugins
        disabled_plugins = { "tohtml", "gzip", "matchit", "zipPlugin", "netrwPlugin", "tarPlugin" },
      },
    },
  },
  presence = {
    -- General options
    auto_update         = true,                       -- Update activity based on autocmd events (if `false`, map or manually execute `:lua package.loaded.presence:update()`)
    neovim_image_text   = "The One True Code Editor", -- Text displayed when hovered over the Neovim image
    main_image          = "neovim",                   -- Main image display (either "neovim" or "file")
    client_id           = "793271441293967371",       -- Use your own Discord application client id (not recommended)
    log_level           = nil,                        -- Log messages at or above this level (one of the following: "debug", "info", "warn", "error")
    debounce_timeout    = 10,                         -- Number of seconds to debounce events (or calls to `:lua package.loaded.presence:update(<filename>, true)`)
    enable_line_number  = false,                      -- Displays the current line number instead of the current project
    blacklist           = {},                         -- A list of strings or Lua patterns that disable Rich Presence if the current file name, path, or workspace matches
    buttons             = true,                       -- Configure Rich Presence button(s), either a boolean to enable/disable, a static table (`{{ label = "<label>", url = "<url>" }, ...}`, or a function(buffer: string, repo_url: string|nil): table)
    file_assets         = {},                         -- Custom file asset definitions keyed by file names and extensions (see default config at `lua/presence/file_assets.lua` for reference)
    show_time           = true,                       -- Show the timer
    -- Rich Presence text options
    editing_text        = "Editing %s",               -- Format string rendered when an editable file is loaded in the buffer (either string or function(filename: string): string)
    file_explorer_text  = "Browsing %s",              -- Format string rendered when browsing a file explorer (either string or function(file_explorer_name: string): string)
    git_commit_text     = "Committing changes",       -- Format string rendered when committing changes in git (either string or function(filename: string): string)
    plugin_manager_text = "Managing plugins",         -- Format string rendered when managing plugins (either string or function(plugin_manager_name: string): string)
    reading_text        = "Reading %s",               -- Format string rendered when a read-only or unmodifiable file is loaded in the buffer (either string or function(filename: string): string)
    workspace_text      = "Working on %s",            -- Format string rendered when in a git repository (either string or function(project_name: string|nil, filename: string): string)
    line_number_text    = "Line %s out of %s",        -- Format string rendered when `enable_line_number` is set to true (either string or function(line_number: number, line_count: number): string)
  },
  -- This function is run last and is a good place to configuring
  -- augroups/autocommands and custom filetypes also this just pure lua so
  -- anything that doesn't fit in the normal config locations above can go here
  polish = function()
    -- Set up custom filetypes
    -- vim.filetype.add {
    --   extension = {
    --     foo = "fooscript",
    --   },
    --   filename = {
    --     ["Foofile"] = "fooscript",
    --   },
    --   pattern = {
    --     ["~/%.config/foo/.*"] = "fooscript",
    --   },
    -- }
  vim.o.scrolloff = 8  -- You can adjust the number to your preference
  vim.o.colorcolumn = "80"  -- You can adjust the number to your preference

  vim.filetype.add {
      extension = {
        tera = "tera",
      },
    }

  vim.filetype.add {
    extension = {
      html = "html",
    }
  }

  local lspconfig = require('lspconfig')
  lspconfig.volar.setup {
    filetypes = { 'typescript', 'javascript', 'javascriptreact', 'typescriptreact', 'vue' },
    init_options = {
      vue = {
        hybridMode = false,
      },
    },
  }

  local dap = require('dap')

    dap.adapters.rust = {
      type = 'executable',
      command = 'lldb-vscode',
      name = "lldb"
    }

    dap.configurations.rust = {
      {
        type = 'rust',
        request = 'launch',
        name = "Launch Rust",
        program = function()
            -- This function allows you to specify the binary to debug.
            -- You can hardcode it or use vim.fn.input to prompt for it.
            return vim.fn.input('Path to executable: ', vim.fn.getcwd() .. '/target/debug/', 'file')
          end,
        cwd = "${workspaceFolder}",
        stopOnEntry = false,
        runtimeArgs = { "run" },
        env = {},
      },
    }
    require("dapui").setup()

    require("tree-sitter-surrealdb").setup()

  end,
}
```

This is AstroNvim init.lua file. I had issue that none of my new or old projects respond to lsp. But after adding this snippet it started to work again with no issues. Is this the solution?

**Comment by wcheek** [comment]
> I solved it with this snippet for 2.x version in my init.lua:
> 
> ```lua
> local lspconfig = require('lspconfig')
>   lspconfig.volar.setup {
>     filetypes = { 'typescript', 'javascript', 'javascriptreact', 'typescriptreact', 'vue' },
>     init_options = {
>       vue = {
>         hybridMode = false,
>       },
>     },
>   }
> ```
> 
> I was not aware of upgrade to 2.x and my problem is fixed by following docs for nvim integration.

@ASoldo you actually solved my problem!

**Comment by ASoldo** [comment]
@wcheek hi, just wanted to share with you config for AstroNvim that works.

I have AstroNvim v4, and with that i have new `plugins/astrolsp.lua` and by adding this config there Volar works great with Vue3 and Nuxt3 projects. For AstroNvim this will be defaulted in the next versions since I raised that issue there.

```lua
...
    -- customize language server configuration options passed to `lspconfig`
    ---@diagnostic disable: missing-fields
    config = {
      volar = {
        filetypes = { "vue" },
        init_options = {
          vue = {
            hybridMode = false,
          },
        },
      },
    },
...
```

**Comment by ASoldo** [comment]
this config doesn't work no more, does anybody know why when i set hybridMode to false i get this. and if I set hybid mode to true it can attach but it is not doing any operations like hover symbol, jump to definitions, rename symbol...

![image](https://github.com/vuejs/language-tools/assets/1175537/9c637dea-ad66-43b1-9d3a-c90468f4f5a9)

```lua
    -- customize language server configuration options passed to `lspconfig`
    ---@diagnostic disable: missing-fields
    config = {
      tsserver = {
        init_options = {
          plugins = {
            {
              name = "@vue/typescript-plugin",
              location = "/usr/lib/node_modules/@vue/typescript-plugin/",
              languages = { "vue" },
            },
          },
        },
      },
      volar = {
        filetypes = { "vue" },
        init_options = {
          vue = {
            hybridMode = false,
          },
        },
      },
    },
```

anybody know how to fix this?

**Comment by so1ve** [comment]
https://github.com/vuejs/language-tools/issues/4520?

**Comment by ASoldo** [comment]
@wcheek does your setup still work?

**Comment by johnsoncodehk** [comment]
> ```lua
>     -- customize language server configuration options passed to `lspconfig`
>     ---@diagnostic disable: missing-fields
>     config = {
>       tsserver = {
>         init_options = {
>           plugins = {
>             {
>               name = "@vue/typescript-plugin",
>               location = "/usr/lib/node_modules/@vue/typescript-plugin/",
>               languages = { "vue" },
>             },
>           },
>         },
>       },
>       volar = {
>         filetypes = { "vue" },
>         init_options = {
>           vue = {
>             hybridMode = false,
>           },
>         },
>       },
>     },
> ```
> 
> anybody know how to fix this?

Not sure if this is the cause, but I found some issues:

- `location = "/usr/lib/node_modules/@vue/typescript-plugin/"` should be `location = "xxx/node_modules/@vue/language-server"`
- `volar.init_options` is missing `typescript.tsdk` option.

**Comment by ASoldo** [comment]
```lua
    config = {
      tsserver = {
        init_options = {
          plugins = {
            {
              name = "@vue/typescript-plugin",
              location = "/usr/lib/node_modules/@vue/language-server/",
              languages = { "vue" },
            },
          },
        },
      },
      volar = {
        filetypes = { "vue" },
        typescript = {
          tsdk = "/usr/lib/node_modules/typescript/lib/",
        },
        init_options = {
          vue = {
            hybridMode = false,
          },
        },
      },
    },
    ```
    This is config I have so far and this is the error i get when I set hybridMode to false:
    ```
    [START][2024-07-04 00:29:04] LSP logging initiated
[ERROR][2024-07-04 00:29:04] .../vim/lsp/rpc.lua:770	"rpc"	"/home/rootster/.local/share/nvim/mason/bin/vue-language-server"	"stderr"	"/home/rootster/.local/share/nvim/mason/packages/vue-language-server/node_modules/@vue/language-server/node_modules/@vue/language-core/lib/languageModule.js:63\n            if (vueCompilerOptions.extensions.some(ext => asFileName(scriptId).endsWith(ext))) {\n                                                          ^\n\nTypeError: asFileName is not a function\n    at /home/rootster/.local/share/nvim/mason/packages/vue-language-server/node_modules/@vue/language-server/node_modules/@vue/language-core/lib/languageModule.js:63:59\n    at Array.some (<anonymous>)\n    at Object.getLanguageId (/home/rootster/.local/share/nvim/mason/packages/vue-language-server/node_modules/@vue/language-server/node_modules/@vue/language-core/lib/languageModule.js:63:47)\n    at Object.set (/home/rootster/.local/share/nvim/mason/packages/vue-language-server/node_modules/@vue/language-server/node_modules/@volar/language-core/index.js:53:60)\n    at /home/rootster/.local/share/nvim/mason/packages/vue-language-server/node_modules/@vue/language-server/node_modules/@volar/language-server/lib/project/typescriptProjectLs.js:83:30\n    at Object.get (/home/rootster/.local/share/nvim/mason/packages/vue-language-server/node_modules/@vue/language-server/node_modules/@volar/language-core/index.js:42:17)\n    at sync (/home/rootster/.local/share/nvim/mason/packages/vue-language-server/node_modules/@vue/language-server/node_modules/@volar/typescript/lib/protocol/createProject.js:171:51)\n    at Object.getProjectVersion (/home/rootster/.local/share/nvim/mason/packages/vue-language-server/node_modules/@vue/language-server/node_modules/@volar/typescript/lib/protocol/createProject.js:81:13)\n    at synchronizeHostData (/home/rootster/Documents/nuxt3-sanity/node_modules/.pnpm/typescript@5.3.3/node_modules/typescript/lib/typescript.js:142750:41)\n    at Object.getProgram (/home/rootster/Documents/nuxt3-sanity/node_modules/.pnpm/typescript@5.3.3/node_modules/typescript/lib/typescript.js:142921:7)\n\nNode.js v22.4.0\n"
```

**Comment by johnsoncodehk** [comment]
@ASoldo What is your `@vue/language-server` version? If it's not the latest, would it be helpful to be more recent to v2.0.24?

**Comment by ASoldo** [comment]
```
❯ vue-language-server --version
2.0.24
```

its the latest.

**Comment by johnsoncodehk** [comment]
@ASoldo Can you try updating to v2.0.26-alpha.2?

**Comment by ASoldo** [comment]
How do i do that since it's not in the npm registry yet?

**Comment by johnsoncodehk** [comment]
> How do i do that since it's not in the npm registry yet?我該怎麼做，因為它還沒有在 npm 註冊表中？

Please try execute `npm install -g @vue/language-server@2.0.26-alpha.2`.

**Comment by ASoldo** [comment]
```
❯ vue-language-server --version
2.0.26-alpha.2
```

It still throws error when loading vue file.

**Comment by wcheek** [comment]
@ASoldo I'm using `LazyVim` these days so I'm not sure how helpful my setup will be for you. I'm depending on the [default configuration](https://www.lazyvim.org/extras/lang/vue) and it's working fine for me with [`vue-language-server@2.0.24`](https://github.com/vuejs/language-tools/tree/v2.0.24) installed via `Mason` and configured with `nvim-lspconfig`:
```lua
{
  "neovim/nvim-lspconfig",
  opts = {
    servers = {
      volar = {
        init_options = {
          vue = {
            hybridMode = false,
          },
        },
      },
      vtsls = {},
    },
  },
}
```

**Comment by ASoldo** [comment]
Once again thank you all for helping me, this is the latest config i have now:
```
    config = {
      tsserver = {
        init_options = {
          plugins = {
            {
              name = "@vue/typescript-plugin",
              location = "/usr/lib/node_modules/@vue/language-server/",
              languages = { "vue" },
            },
          },
        },
      },
      volar = {
        filetypes = { "vue" },
        init_options = {
          typescript = {
            tsdk = "/usr/lib/node_modules/typescript/lib/",
          },
          vue = {
            hybridMode = false,
          },
        },
      },
    },
    ```
but I uninstalled the vue-language-server with Mason and it works now. So take away from this is not to install it with Mason?

**Comment by RayGuo-ergou** [comment]
with `hybridMode = true,` you have to pass the filetype to `vtsls` or `tsserver` that's why it's not working for you.
with `hybridMode = false,` I am also think it's your `tskd` not pass correctly, can you try `which(vue-language-server)` 


btw seems lazyvim's vue config has a performance issue as it set hybrid mode to false but still run a vtsls for vue separately. This will result in 2 typescript lsp running at the same time. I will create an issue or PR later. ( you can also do if you want to :) )

**Comment by ASoldo** [comment]
```
❯ which vue-language-server
/usr/bin/vue-language-server
```
This is what i have and also removed vue-language-server(volar) from Mason.

**Comment by RayGuo-ergou** [comment]
ops my bad `tskd` should be `typescript` not vue language server.

**Comment by RayGuo-ergou** [comment]
maybe try to remove tsdk as `lspconfig.nvim` will automatically find the path.

https://github.com/neovim/nvim-lspconfig/blob/master/lua/lspconfig/server_configurations/volar.lua#L21-L30

**Comment by jblyberg** [comment]
I am also getting this error. Using LazyVim with volar in hybrid mode and vtsls disabled.

```
Client volar quit with exit code 1 and signal 0. Check log for errors: /Users/<my username>/.local/state/nvim/lsp.log
```

Output of `lsp.log`:

```
[ERROR][2024-07-03 21:02:36] .../vim/lsp/rpc.lua:770	"rpc"	"/Users/myhome/.local/share/nvim/mason/bin/vue-language-server"	"stderr"	"/Users/myhome/.local/share/nvim/mason/packages/vue-language-server/node_modules/@vue/language-server/node_modules/@vue/language-core/lib/languageModule.js:63\n            if (vueCompilerOptions.extensions.some(ext => asFileName(scriptId).endsWith(ext))) {\n                                                          ^\n\nTypeError: asFileName is not a function\n    at /Users/myhome/.local/share/nvim/mason/packages/vue-language-server/node_modules/@vue/language-server/node_modules/@vue/language-core/lib/languageModule.js:63:59\n    at Array.some (<anonymous>)\n    at Object.getLanguageId (/Users/myhome/.local/share/nvim/mason/packages/vue-language-server/node_modules/@vue/language-server/node_modules/@vue/language-core/lib/languageModule.js:63:47)\n    at Object.set (/Users/myhome/.local/share/nvim/mason/packages/vue-language-server/node_modules/@vue/language-server/node_modules/@volar/language-core/index.js:53:60)\n    at /Users/myhome/.local/share/nvim/mason/packages/vue-language-server/node_modules/@vue/language-server/node_modules/@volar/language-server/lib/project/typescriptProjectLs.js:83:30\n    at Object.get (/Users/myhome/.local/share/nvim/mason/packages/vue-language-server/node_modules/@vue/language-server/node_modules/@volar/language-core/index.js:42:17)\n    at sync (/Users/myhome/.local/share/nvim/mason/packages/vue-language-server/node_modules/@vue/language-server/node_modules/@volar/typescript/lib/protocol/createProject.js:171:51)\n    at Object.getProjectVersion (/Users/myhome/.local/share/nvim/mason/packages/vue-language-server/node_modules/@vue/language-server/node_modules/@volar/typescript/lib/protocol/createProject.js:81:13)\n    at synchronizeHostDataWorker (/Users/myhome/code/projects/inkleaf/ui-intranet/node_modules/.pnpm/typescript@5.5.2/node_modules/typescript/lib/typescript.js:148836:39)\n    at synchronizeHostData (/Users/myhome/code/projects/inkleaf/ui-intranet/node_modules/.pnpm/typescript@5.5.2/node_modules/typescript/lib/typescript.js:148829:7)\n\nNode.js v22.4.0\n"
```

My lsp config:

```
        volar = {
          init_options = {
            vue = {
              hybridMode = false,
            },
          },
        },
```

**Comment by RayGuo-ergou** [comment]
Also tried with `2.0.24`, it's indeed crash, but upgrade to `2.0.26 alpha2` works fine for me.

**Comment by jblyberg** [comment]
Can confirm that `2.0.26-alpha.2` works for me as well.

**Comment by hirotaka** [comment]
I'm using LazyVim and Vue Extra.  I installed it via Mason, and it worked for me.

```
:MasonInstall vue-language-server@2.0.26-alpha.2
```

**Comment by ASoldo** [comment]
> I'm using LazyVim and Vue Extra. I installed it via Mason, and it worked for me.
> 
> ```
> :MasonInstall vue-language-server@2.0.26-alpha.2
> ```

I've done the same and it works just by having this:
```
   volar = {
        filetypes = { "vue" },
        init_options = {
          vue = {
            hybridMode = false,
          },
        },
      },
```
So is it a bug with 2.0.24?

**Comment by hirotaka** [comment]
In my case, the error occurred when I upgraded the project's Typescript version from 4 to 5.
I've not checked properly, but I suspect this problem is related to the 2.0.24 and Typescript versions.

**Comment by wcheek** [comment]
> with `hybridMode = true,` you have to pass the filetype to `vtsls` or `tsserver` that's why it's not working for you. with `hybridMode = false,` I am also think it's your `tskd` not pass correctly, can you try `which(vue-language-server)`
> 
> btw seems lazyvim's vue config has a performance issue as it set hybrid mode to false but still run a vtsls for vue separately. This will result in 2 typescript lsp running at the same time. I will create an issue or PR later. ( you can also do if you want to :) )

I'd really appreciate if you did - I've noticed the duplicate diagnostics in `vue` files ever since `LazyVim` moved to `vtsls` but haven't had the expertise to properly diagnose and file an issue about it.

**Comment by RayGuo-ergou** [comment]
I have created a PR in lazyvim: https://github.com/LazyVim/LazyVim/pull/3908

**Comment by ASoldo** [comment]
Since update `2.0.26` everything seems to be in order for Nuxt/Vue projects and Js/Ts projects. I have successfully updated lsp with Mason. I'm really glad it's fixed now!
