### ISSUE TITLE
Debug Failure. Did not expect ImportDeclaration to have an Identifier in its trivia

### ISSUE THREAD

**Issue by samuliraty** [vuejs/language-tools#4271]
In neovim i get bombarded with:

```ps1
tsserver: 1: <semantic> TypeScript Server Error (5.3.3)
Debug Failure. Did not expect ImportDeclaration to have an Identifier in its trivia
Error: Debug Failure. Did not expect ImportDeclaration to have an Identifier in its trivia
    at addSyntheticNodes (c:\x\y\z\z.foo\bar\node_modules\typescript\lib\tsserver.js:143992:15)
    at processNode (c:\x\y\z\z.foo\bar\node_modules\typescript\lib\tsserver.js:143966:5)
    at visitNode2 (c:\x\y\z\z.foo\bar\node_modules\typescript\lib\tsserver.js:30227:18)
    at forEachChildInImportDeclaration (c:\x\y\z\z.foo\bar\node_modules\typescript\lib\tsserver.js:30533:59)
    at NodeObject.forEachChild (c:\x\y\z\z.foo\bar\node_modules\typescript\lib\tsserver.js:143949:12)
    at createChildren (c:\x\y\z\z.foo\bar\node_modules\typescript\lib\tsserver.js:143977:8)
    at NodeObject.getChildren (c:\x\y\z\z.foo\bar\node_modules\typescript\lib\tsserver.js:143928:48)
    at getTokenAtPositionWorker (c:\x\y\z\z.foo\bar\node_modules\typescript\lib\tsserver.js:132140:32)
    at getTouchingToken (c:\x\y\z\z.foo\bar\node_modules\typescript\lib\tsserver.js:132113:10)
    at getTouchingPropertyName (c:\x\y\z\z.foo\bar\node_modules\typescript\lib\tsserver.js:132110:10)
    at getReferencesAtLocation (c:\x\y\z\z.foo\bar\node_modules\typescript\lib\tsserver.js:163581:31)
    at getReferencesInContainer (c:\x\y\z\z.foo\bar\node_modules\typescript\lib\tsserver.js:163574:7)
    at getReferencesInContainerOrFiles (c:\x\y\z\z.foo\bar\node_modules\typescript\lib\tsserver.js:163157:7)
    at getReferencedSymbolsForSymbol (c:\x\y\z\z.foo\bar\node_modules\typescript\lib\tsserver.js:163150:7)
    at Object.getReferencedSymbolsForNode (c:\x\y\z\z.foo\bar\node_modules\typescript\lib\tsserver.js:162897:24)
    at Object.getReferenceEntriesForNode (c:\x\y\z\z.foo\bar\node_modules\typescript\lib\tsserver.js:162541:30)
    at getSemanticDocumentHighlights (c:\x\y\z\z.foo\bar\node_modules\typescript\lib\tsserver.js:135411:59)
    at Object.getDocumentHighlights (c:\x\y\z\z.foo\bar\node_modules\typescript\lib\tsserver.js:135399:12)
    at getDocumentHighlights (c:\x\y\z\z.foo\bar\node_modules\typescript\lib\tsserver.js:145195:31)
    at C:\x\y\z\z.foo\bar\node_modules\@volar\typescript\lib\node\decorateLanguageService.js:204:120
    at process (C:\x\y\z\z.foo\bar\node_modules\@volar\typescript\lib\node\decorateLanguageService.js:609:28)
    at linkedCodeFeatureWorker (C:\x\y\z\z.foo\bar\node_modules\@volar\typescript\lib\node\decorateLanguageService.js:596:21)
    at languageService.getDocumentHighlights (C:\x\y\z\z.foo\bar\node_modules\@volar\typescript\lib\node\decorateLanguageService.js:204:28)
    at IpcIOSession.getDocumentHighlights (c:\x\y\z\z.foo\bar\node_modules\typescript\lib\tsserver.js:184178:61)
    at documentHighlights (c:\x\y\z\z.foo\bar\node_modules\typescript\lib\tsserver.js:183149:43)
    at c:\x\y\z\z.foo\bar\node_modules\typescript\lib\tsserver.js:185375:69
    at IpcIOSession.executeWithRequestId (c:\x\y\z\z.foo\bar\node_modules\typescript\lib\tsserver.js:185367:14)
    at IpcIOSession.executeCommand (c:\x\y\z\z.foo\bar\node_modules\typescript\lib\tsserver.js:185375:29)
    at IpcIOSession.onMessage (c:\x\y\z\z.foo\bar\node_modules\typescript\lib\tsserver.js:185417:51)
    at process.<anonymous> (c:\x\y\z\z.foo\bar\node_modules\typescript\lib\tsserver.js:186999:14)
    at process.emit (node:events:514:28)
    at emit (node:internal/child_process:937:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
```

Project Dependencies:
```json
...
    "dependencies": {
        "@headlessui/vue": "^1.7.19",
        "pinia": "^2.1.7",
        "validator": "^13.11.0",
        "vue": "^3.3.11",
        "vue-i18n": "^9.9.1",
        "vue-router": "^4.2.5"
    },
    "devDependencies": {
        "@total-typescript/ts-reset": "^0.5.1",
        "@tsconfig/node18": "^18.2.2",
        "@types/node": "^18.19.3",
        "@types/validator": "^13.11.9",
        "@vitejs/plugin-vue": "^4.5.2",
        "@vue/tsconfig": "^0.5.0",
        "@vue/typescript-plugin": "^2.0.13",
        "autoprefixer": "^10.4.17",
        "npm-run-all2": "^6.1.1",
        "postcss": "^8.4.33",
        "prettier": "^3.2.4",
        "tailwindcss": "^3.4.1",
        "typescript": "~5.3.0",
        "vite": "^5.0.10",
        "vue-tsc": "^1.8.25"
    }
...
```

neovim config (init.lua)
```lua
...
        tsserver = {
          init_options = {
            plugins = {
              {
                name = '@vue/typescript-plugin',
                location = '...',
                languages = { 'vue' },
              },
            },
          },
...
```

_Originally posted by @samuliraty in https://github.com/vuejs/language-tools/issues/4246#issuecomment-2056368492_

**Comment by samuliraty** [comment]
Closing as removing the following from my config ended the issue:

```lua
local client = vim.lsp.get_client_by_id(event.data.client_id)
if client and client.server_capabilities.documentHighlightProvider then
  vim.api.nvim_create_autocmd({ 'CursorHold', 'CursorHoldI' }, {
    buffer = event.buf,
    callback = vim.lsp.buf.document_highlight,
  })

  vim.api.nvim_create_autocmd({ 'CursorMoved', 'CursorMovedI' }, {
    buffer = event.buf,
    callback = vim.lsp.buf.clear_references,
  })
end
```

**Comment by gin-18** [comment]
I have removed the code from my config but still got the error when I called `vim.lsp.buf.references`.

**Comment by samuliraty** [comment]
Agreed, did not and do not have time to investigate this further, but what I did does not fix the issue, only got rid of the worst symptoms for me.

I will reopen this issue since you are still experiencing it.

**Comment by johnsoncodehk** [comment]
This should fixed by https://github.com/volarjs/volar.js/commit/f0aad5d7d0e86e414a602c1afe84dcf9eb5ac78b, please update `@vue/typescript-plugin` to 2.0.14 or later.
