### ISSUE TITLE
Crush after update typescript to 5.5

### ISSUE THREAD

**Issue by mrquokka** [vuejs/language-tools#4484]
### Vue - Official extension or vue-tsc version

vue-tsc

### VSCode version

1.90.1

### Vue version

3.4.29

### TypeScript version

5.5

### Steps to reproduce

Just upgrade to typescript 5.5

### Any additional comments?

npm run build 

> npm-project-beta@6.4.0-dev1 build
> vue-tsc && vite build

.../node_modules/vue-tsc/bin/vue-tsc.js:68
			throw err;
			^
Search string not found: "for (const existingRoot of buildInfoVersionMap.roots) {"
(Use `node --trace-uncaught ...` to show where the exception was thrown)

Node.js v20.5.1

**Comment by fit2-zhao** [comment]
Me too, same question.


[INFO] Search string not found: "for (const existingRoot of buildInfoVersionMap.roots) {"
[INFO] (Use `node --trace-uncaught ...` to show where the exception was thrown)
[INFO] 
[INFO] Node.js v20.8.1

**Comment by StreakingMan** [comment]
Same problem...typescirpt 5.4 works but 5.5 not work

**Comment by daniluk4000** [comment]
@johnsoncodehk

**Comment by johnsoncodehk** [comment]
This is v1 error message, please make sure update `vue-tsc` to v2.

**Comment by daniluk4000** [comment]
> This is v1 error message, please make sure update `vue-tsc` to v2.

Due to https://github.com/fi3ework/vite-plugin-checker/issues/306 we still can't update :(

**Comment by johnsoncodehk** [comment]
Please track for https://github.com/fi3ework/vite-plugin-checker/pull/327.

**Comment by jaxenvisuals** [comment]
> This is v1 error message, please make sure update `vue-tsc` to v2.

Worked for me

**Comment by santokhan** [comment]
> This is v1 error message, please make sure update `vue-tsc` to v2.

It works for me. But it requires to change the version manually. 
Thank you [johnsoncodehk](https://github.com/johnsoncodehk)

**Comment by wangliangxin** [comment]
> This is v1 error message, please make sure update `vue-tsc` to v2.

It works for me

**Comment by stephanestermann** [comment]
Same here:
"vue-tsc": "^2.1.10" not work with "typescript": "~5.7.2",
![image](https://github.com/user-attachments/assets/9cb4b933-081c-4780-8e2e-4e6b64fa5b15)

**Comment by MartinsOnuoha** [comment]
Yes downgrading to typescript `5.6.3` worked for me too. 

```
npm i --save-dev typescript@~5.6.3
```

**Comment by toniengelhardt** [comment]
Same issue with typescript `5.7.2`, with `5.6.3` it works.

**Comment by zemkogabor** [comment]
Same issue with typescript `5.7.2`, with `5.6.3` another error (`vue-tsc 2.1.10`):

```
yarn run v1.22.22
$ vue-tsc --build --verbose
[3:19:18 PM] Projects in this build: 
    * tsconfig.node.json
    * tsconfig.app.json
    * tsconfig.json

[3:19:18 PM] Project 'tsconfig.node.json' is out of date because output file 'node_modules/.tmp/tsconfig.node.tsbuildinfo' does not exist

[3:19:18 PM] Building project '/app/tsconfig.node.json'...

[3:19:19 PM] Project 'tsconfig.app.json' is out of date because output file 'node_modules/.tmp/tsconfig.app.tsbuildinfo' does not exist

[3:19:19 PM] Building project '/app/tsconfig.app.json'...

/app/node_modules/vue-tsc/index.js:34
            throw err;
            ^

Error: Debug Failure.
    at visitEachChildOfIndexSignatureDeclaration (/app/node_modules/typescript/lib/tsc.js:88839:13)
    at visitEachChild (/app/node_modules/typescript/lib/tsc.js:88695:33)
    at visitEachChild2 (/app/node_modules/typescript/lib/tsc.js:52363:18)
    at visitExistingNodeTreeSymbolsWorker (/app/node_modules/typescript/lib/tsc.js:52251:25)
    at visitExistingNodeTreeSymbols (/app/node_modules/typescript/lib/tsc.js:51943:24)
    at visitArrayWorker (/app/node_modules/typescript/lib/tsc.js:88509:49)
    at visitNodes2 (/app/node_modules/typescript/lib/tsc.js:88480:19)
    at visitNodesWithoutCopyingPositions (/app/node_modules/typescript/lib/tsc.js:52372:24)
    at visitEachChildOfTypeLiteralNode (/app/node_modules/typescript/lib/tsc.js:88885:7)
    at visitEachChild (/app/node_modules/typescript/lib/tsc.js:88695:33)

Node.js v22.11.0
```

**Comment by silverwind** [comment]
Yep, broken with typescript 5.7:

```
node_modules/vue-tsc/index.js:34
            throw err;
            ^
Search string not found: "/supportedTSExtensions = .*(?=;)/"
```

Imho it's time to upstream the module into `tsc` and deprecate `vue-tsc`.

**Comment by sinedied** [comment]
Could this issue be reopened?  as it occurs again with latest typescript version
