### ISSUE TITLE
Using a LESS variable as a class name and writing styles inside it caused the Vue server to crash.

### ISSUE THREAD

**Issue by oneness0** [vuejs/language-tools#4712]
### Vue - Official extension or vue-tsc version

2.0.28

### VSCode version

1.92.2

### Vue version

3.4.32

### TypeScript version

5.5.4

### System Info

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
    Memory: 1.21 GB / 15.69 GB
  Binaries:
    Node: 20.16.0 - ~\AppData\Local\Volta\tools\image\node\20.16.0\node.EXE
    Yarn: 1.22.22 - ~\AppData\Local\Volta\tools\image\yarn\1.22.22\bin\yarn.CMD
    npm: 10.8.1 - ~\AppData\Local\Volta\tools\image\node\20.16.0\npm.CMD
    pnpm: 9.7.0 - ~\AppData\Local\Volta\tools\image\pnpm\9.7.0\bin\pnpm.CMD
    bun: 1.1.25 - ~\.bun\bin\bun.EXE
  Browsers:
    Edge: Chromium (127.0.2651.74), ChromiumDev (127.0.2610.3)
    Internet Explorer: 11.0.22621.3527
```

#### code:
```css
<style lang="less" scoped>
@prefix-cls: 'edit-faq-drawerr';
.@{prefix-cls} {
  width: 22px;
  height: auto;
  ...Crash when writing some CSS styles.
}
</style>
```
#### error info:
```
TypeError: Cannot read properties of undefined (reading 'type')
    at Q2e (c:\Users\www20\.vscode\extensions\vue.volar-2.0.28\dist\server.js:288:29911)
    at bAe (c:\Users\www20\.vscode\extensions\vue.volar-2.0.28\dist\server.js:312:15547)
    at r (c:\Users\www20\.vscode\extensions\vue.volar-2.0.28\dist\server.js:312:17780)
    at async m (c:\Users\www20\.vscode\extensions\vue.volar-2.0.28\dist\server.js:2:48931)
    at async Object.getCompletionItems (c:\Users\www20\.vscode\extensions\vue.volar-2.0.28\dist\server.js:2:49695)
    at async c:\Users\www20\.vscode\extensions\vue.volar-2.0.28\dist\server.js:66:20313
    at async Timeout.<anonymous> (c:\Users\www20\.vscode\extensions\vue.volar-2.0.28\dist\server.js:66:26851)

Node.js v20.14.0
[Error - 10:20:24] Server process exited with code 1.
```

### What is expected?

No crash, and CSS properties are properly suggested.

### What is actually happening?

The Vue server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
![image](https://github.com/user-attachments/assets/dc581341-3862-416d-bb5d-7dc3149a578f)

**Comment by rex-ll** [comment]
me too
