### ISSUE TITLE
Vanilla install does not work at all

### ISSUE THREAD

**Issue by rocifier** [vuejs/language-tools#4993]
### Vue - Official extension or vue-tsc version

2.1.10

### VSCode version

1.95.x

### Vue version

3.4.33

### TypeScript version

5.3.3

### System Info

```shell
I've started with a clean install of windows
- no user settings.json present
- no project/workspace settings present
- older project which started at vue 3.1 and has been upgraded consistently on schedule

envinfo:
  System:
    OS: Windows 10 10.0.17763
    CPU: (4) x64 Intel(R) Xeon(R) Gold 6138 CPU @ 2.00GHz
    Memory: 7.40 GB / 16.00 GB
  Binaries:
    Node: 20.11.1 - C:\Program Files\nodejs\node.EXE
    npm: 10.2.4 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 130.0.6723.92
```

### package.json dependencies

```json
{
  "name": "orbit-app",
  "version": "0.1.0",
  "private": true,
  "type": "module",
  "lint-staged": {
    "*.{vue,js,jsx,cjs,mjs,ts,tsx,cts,mts,css,md}": "prettier --write"
  },
  "scripts": {
    "dev": "vite",
    "build": "vite build --outDir ../wwwroot --emptyOutDir",
    "buildPipeline": "vite build --debug --emptyOutDir",
    "dockerbuild": "vue-tsc --noEmit && vite build",
    "preview": "vite preview --port 3000",
    "typecheck": "vue-tsc --noEmit",
    "lint": "eslint ./src/ --ext .vue,.js,.jsx,.cjs,.mjs,.ts,.tsx,.cts,.mts --fix --ignore-path .gitignore",
    "prepare": "cd ../../.. && husky install src/T3.Orbit/ClientApp/.husky",
    "test": "vitest",
    "coverage": "vitest run --coverage"
  },
  "dependencies": {
    "@fullstory/browser": "^2.0.1",
    "@gtm-support/vue-gtm": "^2.2.0",
    "@highlightjs/vue-plugin": "^2.1.0",
    "@microsoft/signalr": "^8.0.0",
    "@sentry/vite-plugin": "^2.21.1",
    "@sentry/vue": "^8.33.1",
    "@t3i-tahi-bss/tahi-frontend-lib": "^1.1.0",
    "@types/bootstrap": "^5.2.10",
    "@types/dateformat": "^5.0.2",
    "@types/qrcode": "^1.5.5",
    "@types/signalr": "^2.4.3",
    "@types/vue-select": "^3.16.8",
    "@vuelidate/core": "^2.0.3",
    "@vuelidate/validators": "^2.0.4",
    "@vuepic/vue-datepicker": "^7.4.0",
    "async-lock": "^1.4.1",
    "bootstrap": "^5.3.2",
    "dagre": "^0.8.5",
    "date-holidays": "^3.23.12",
    "dayjs": "^1.11.10",
    "decimal.js": "^10.4.3",
    "docx": "^8.5.0",
    "file-saver": "^2.0.5",
    "fuse.js": "^7.0.0",
    "gridstack": "^10.0.1",
    "handlebars": "^4.7.8",
    "highcharts": "^11.2.0",
    "highcharts-vue": "^1.4.3",
    "highlight.js": "^11.9.0",
    "jsonpath": "^1.1.1",
    "libphonenumber-js": "^1.10.53",
    "maska": "^2.1.10",
    "pinia": "^2.1.7",
    "qrcode": "^1.5.3",
    "sass": "^1.69.7",
    "signature_pad": "^4.1.7",
    "v-network-graph": "^0.9.14",
    "vue": "^3.4.33",
    "vue-currency-input": "^3.0.5",
    "vue-router": "^4.3.0",
    "vue-select": "^4.0.0-beta.5",
    "vue3-lottie": "^3.2.0"
  },
  "devDependencies": {
    "@babel/types": "^7.23.6",
    "@edge-runtime/vm": "^3.1.7",
    "@playwright/test": "^1.40.1",
    "@rushstack/eslint-patch": "^1.6.1",
    "@tsconfig/node18": "^18.2.2",
    "@types/async-lock": "^1.4.2",
    "@types/file-saver": "^2.0.7",
    "@types/node": "^20.10.7",
    "@types/vue-select": "^3.16.8",
    "@vitejs/plugin-vue": "^5.0.2",
    "@vitest/coverage-v8": "^1.1.3",
    "@vue/eslint-config-typescript": "^12.0.0",
    "@vue/test-utils": "^2.4.3",
    "@vue/tsconfig": "^0.5.1",
    "esbuild": "^0.19.11",
    "eslint": "^8.57.0",
    "eslint-config-prettier": "^9.1.0",
    "eslint-plugin-vue": "^9.22.0",
    "happy-dom": "^12.10.3",
    "husky": "^8.0.3",
    "jsdom": "^23.2.0",
    "lint-staged": "^15.2.9",
    "prettier": "3.1.1",
    "typescript": "^5.3.3",
    "vite": "^5.0.13",
    "vitest": "^1.1.3",
    "vue-tsc": "^2.1.4"
  }
}
```

### Steps to reproduce

Install current .vscode version
Install vue - official extension (ensure no other extensions are installed)

### What is expected?

When editing a .vue file in vscode, both syntax highlighting and typescript errors should be shown in-line in the file. Vue and TS should have language servers running which have logs.

### What is actually happening?

There is colour coding in the file but no syntax highlighting. I can save files with obvious syntactical error and the problems are never highlighted in any way in the IDE, including in the Problems window.
There are no language servers running.
Manually restarting the language servers with Ctrl+Alt+P and 'Restart Vue and Typescript language servers...' results in a vscode alert that says 'vue.action.restartServer' not found.

There is an error repeatedly shown under Extension Host in vscode command outputs:
```
2024-11-07 17:18:22.600 [error] Error: [ExtensionListenerError] Extension 'Vue.volar' FAILED to handle event: TypeError: Cannot read properties of undefined (reading 'includes')
    at mh.value (file:///c:/Users/Ryan.Oconnor/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:156:35379)
    at D.B (file:///c:/Users/Ryan.Oconnor/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:746)
    at D.C (file:///c:/Users/Ryan.Oconnor/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:816)
    at D.fire (file:///c:/Users/Ryan.Oconnor/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:1033)
    at mh.value (file:///c:/Users/Ryan.Oconnor/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:155:61555)
    at D.B (file:///c:/Users/Ryan.Oconnor/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:746)
    at D.fire (file:///c:/Users/Ryan.Oconnor/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:964)
    at Sw.acceptDocumentsAndEditorsDelta (file:///c:/Users/Ryan.Oconnor/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:121:11570)
    at Sw.$acceptDocumentsAndEditorsDelta (file:///c:/Users/Ryan.Oconnor/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:121:10040)
    at py.S (file:///c:/Users/Ryan.Oconnor/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:31:113311)
    at py.Q (file:///c:/Users/Ryan.Oconnor/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:31:113091)
    at py.M (file:///c:/Users/Ryan.Oconnor/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:31:112180)
    at py.L (file:///c:/Users/Ryan.Oconnor/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:31:111285)
    at mh.value (file:///c:/Users/Ryan.Oconnor/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:31:110082)
    at D.B (file:///c:/Users/Ryan.Oconnor/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:746)
    at D.fire (file:///c:/Users/Ryan.Oconnor/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:964)
    at Vn.fire (file:///c:/Users/Ryan.Oconnor/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:31:9457)
    at mh.value (file:///c:/Users/Ryan.Oconnor/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:174:13279)
    at D.B (file:///c:/Users/Ryan.Oconnor/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:746)
    at D.fire (file:///c:/Users/Ryan.Oconnor/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:964)
    at Vn.fire (file:///c:/Users/Ryan.Oconnor/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:31:9457)
    at MessagePortMain.<anonymous> (file:///c:/Users/Ryan.Oconnor/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:174:11571)
    at MessagePortMain.emit (node:events:519:28)
    at Object.MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:2949)
```

### Any additional comments?

This extension has not worked since 2.0.8, and today I decide to try a blank windows install and log exactly why. I ran vscode with Administrator privileges, as is now required.

**Comment by chanlito** [comment]
Might be your typescript version?

**Comment by KazariEX** [comment]
Is this still a problem?
